import {
  PromotionProgramType,
  PromotionStatus,
  PromotionApplyTo,
  PromotionBirthdayMatch,
  PromotionDiscountMode,
  PromotionInvoiceScope,
  PromotionTierBasis,
  PromotionTierScope,
  PromotionTargetType,
  PromotionGiftMode,
  PromotionBuyGetPolicy,
  PromotionLineRole,
} from '@erp/shared-interfaces';
import { TimeOfDay } from './value-objects/time-window';
import { PromotionGroup } from './promotion-group';
import { PromotionCondition } from './promotion-condition';
import { DomainValidationError, DomainValidationIssue } from './domain-error';

export interface PromotionProgramProps {
  /** Undefined for an aggregate that has not been persisted yet. */
  id?: string;
  organizationId: string;
  /** Generated by DocumentNumberingService before create() is called. */
  code: string;
  name: string;
  description?: string;
  type: PromotionProgramType;
  status: PromotionStatus;
  priority: number;
  applyTo: PromotionApplyTo;
  birthdayMatch?: PromotionBirthdayMatch;
  birthdayBeforeDays?: number;
  birthdayAfterDays?: number;
  cardTierId?: string;
  customerGroupIds: string[];
  startDate?: Date;
  endDate?: Date;
  daysOfWeek: number[];
  startTime?: TimeOfDay;
  endTime?: TimeOfDay;
  autoApply: boolean;
  /** promotion_branches — empty = whole chain (BR-005). */
  branchIds: string[];
  invoiceScope?: PromotionInvoiceScope;
  accruePoints: boolean;
  discountMode?: PromotionDiscountMode;
  discountValue?: number;
  maxDiscountAmount?: number;
  tierBasis?: PromotionTierBasis;
  tierScope?: PromotionTierScope;
  targetType?: PromotionTargetType;
  giftMode?: PromotionGiftMode;
  buyGetPolicy?: PromotionBuyGetPolicy;
  buyQuantity?: number;
  giftQuantity?: number;
  groups: PromotionGroup[];
  condition?: PromotionCondition;
  createdBy: string;
  createdAt?: Date;
  updatedAt?: Date;
}

function validateDiscountAmount(
  mode: PromotionDiscountMode | undefined,
  value: number | undefined,
  field: string,
  issues: DomainValidationIssue[],
): void {
  if (value === undefined) return;
  if (value <= 0) {
    issues.push({
      field,
      code: 'DISCOUNT_VALUE_NOT_POSITIVE',
      message: `${field} must be greater than 0`,
    });
  }
  if (mode === PromotionDiscountMode.PERCENT && value > 100) {
    issues.push({
      field,
      code: 'PERCENT_OVER_100',
      message: `${field} cannot exceed 100 when discount mode is PERCENT`,
    });
  }
}

function validateTierRanges(group: PromotionGroup, issues: DomainValidationIssue[]): void {
  const sorted = [...group.tiers].sort((a, b) => a.fromValue - b.fromValue);

  for (let i = 0; i < sorted.length; i += 1) {
    const tier = sorted[i];

    if (tier.toValue !== undefined && tier.fromValue >= tier.toValue) {
      issues.push({
        field: `tiers[${tier.id}]`,
        code: 'TIER_RANGE_INVALID',
        message: `Tier fromValue must be less than toValue`,
      });
      continue;
    }

    const next = sorted[i + 1];
    if (!next) continue;

    const overlaps = tier.toValue === undefined || next.fromValue < tier.toValue;
    if (overlaps) {
      issues.push({
        field: `tiers[${next.id}]`,
        code: 'TIER_RANGE_OVERLAP',
        message: `Tier range overlaps with a preceding tier`,
      });
    }
  }
}

function validate(props: PromotionProgramProps): DomainValidationIssue[] {
  const issues: DomainValidationIssue[] = [];

  if (!props.name || props.name.trim().length === 0) {
    issues.push({ field: 'name', code: 'NAME_REQUIRED', message: 'Name is required' });
  }

  if (props.startDate && props.endDate && props.endDate < props.startDate) {
    issues.push({
      field: 'endDate',
      code: 'END_DATE_BEFORE_START_DATE',
      message: 'End date must not be before start date',
    });
  }

  if (props.applyTo === PromotionApplyTo.CUSTOMER_GROUP && props.customerGroupIds.length === 0) {
    issues.push({
      field: 'customerGroupIds',
      code: 'CUSTOMER_GROUP_IDS_EMPTY',
      message: 'At least one customer group is required when apply-to is CUSTOMER_GROUP',
    });
  }
  if (props.applyTo === PromotionApplyTo.CARD_TIER && !props.cardTierId) {
    issues.push({
      field: 'cardTierId',
      code: 'CARD_TIER_ID_REQUIRED',
      message: 'Card tier is required when apply-to is CARD_TIER',
    });
  }
  // BIRTHDAY had no companion-field rule while CUSTOMER_GROUP and CARD_TIER
  // did, so a birthday promotion saved without a match kind and then never
  // matched anyone — CustomerScope.matchesBirthday falls through to `false`.
  if (props.applyTo === PromotionApplyTo.BIRTHDAY && !props.birthdayMatch) {
    issues.push({
      field: 'birthdayMatch',
      code: 'BIRTHDAY_MATCH_REQUIRED',
      message: 'Birthday match kind is required when apply-to is BIRTHDAY',
    });
  }

  // Every strategy reads groups[0]; a programme with no group at all reached
  // the engine and threw, turning one bad row into a 500 on every checkout.
  // Blocked here so it can never be stored again — the strategies also guard
  // defensively for rows saved before this rule existed.
  if (props.groups.length === 0) {
    issues.push({
      field: 'groups',
      code: 'GROUPS_EMPTY',
      message: 'At least one group is required',
    });
  }

  if (props.type === PromotionProgramType.INVOICE_DISCOUNT) {
    validateDiscountAmount(props.discountMode, props.discountValue, 'discountValue', issues);
  }

  const rewardLines = props.groups.flatMap((group) => group.lines).filter(
    (line) => line.role === PromotionLineRole.REWARD,
  );
  for (const line of rewardLines) {
    validateDiscountAmount(line.discountMode, line.discountValue, `lines[${line.id}].discountValue`, issues);
  }

  const requiresRewardLines = !(
    props.type === PromotionProgramType.INVOICE_DISCOUNT ||
    (props.type === PromotionProgramType.TIERED_DISCOUNT &&
      props.tierBasis === PromotionTierBasis.INVOICE_VALUE) ||
    // CHEAPEST gifts the cheapest of the CONDITION lines themselves — it never
    // populates a separate reward grid (amdt KM-04, see KM-05's strategy notes).
    (props.type === PromotionProgramType.BUY_M_GET_N &&
      props.buyGetPolicy === PromotionBuyGetPolicy.CHEAPEST)
  );
  if (requiresRewardLines && rewardLines.length === 0) {
    issues.push({
      field: 'groups',
      code: 'REWARD_LINES_EMPTY',
      message: 'At least one reward line is required for this promotion type',
    });
  }

  if (props.type === PromotionProgramType.TIERED_DISCOUNT) {
    const allTiers = props.groups.flatMap((group) => group.tiers);
    if (allTiers.length === 0) {
      issues.push({
        field: 'groups',
        code: 'TIERS_EMPTY',
        message: 'At least one tier is required for TIERED_DISCOUNT',
      });
    }
    for (const group of props.groups) {
      validateTierRanges(group, issues);
      for (const tier of group.tiers) {
        validateDiscountAmount(tier.discountMode, tier.discountValue, `tiers[${tier.id}].discountValue`, issues);
      }
    }
  }

  if (props.type === PromotionProgramType.BUY_M_GET_N && props.buyGetPolicy === PromotionBuyGetPolicy.CHEAPEST) {
    if (!props.buyQuantity || props.buyQuantity <= 0) {
      issues.push({
        field: 'buyQuantity',
        code: 'BUY_QUANTITY_INVALID',
        message: 'Buy quantity must be greater than 0',
      });
    }
    if (!props.giftQuantity || props.giftQuantity <= 0) {
      issues.push({
        field: 'giftQuantity',
        code: 'GIFT_QUANTITY_INVALID',
        message: 'Gift quantity must be greater than 0',
      });
    }
  }

  return issues;
}

/**
 * Aggregate root for a CTKM. Immutable once created — there is no public
 * setter; an "edit" is a fresh `create()` call with merged props that
 * re-validates the whole aggregate.
 */
export class PromotionProgram {
  readonly id?: string;
  readonly organizationId: string;
  readonly code: string;
  readonly name: string;
  readonly description?: string;
  readonly type: PromotionProgramType;
  readonly status: PromotionStatus;
  readonly priority: number;
  readonly applyTo: PromotionApplyTo;
  readonly birthdayMatch?: PromotionBirthdayMatch;
  readonly birthdayBeforeDays?: number;
  readonly birthdayAfterDays?: number;
  readonly cardTierId?: string;
  readonly customerGroupIds: string[];
  readonly startDate?: Date;
  readonly endDate?: Date;
  readonly daysOfWeek: number[];
  readonly startTime?: TimeOfDay;
  readonly endTime?: TimeOfDay;
  readonly autoApply: boolean;
  readonly branchIds: string[];
  readonly invoiceScope?: PromotionInvoiceScope;
  readonly accruePoints: boolean;
  readonly discountMode?: PromotionDiscountMode;
  readonly discountValue?: number;
  readonly maxDiscountAmount?: number;
  readonly tierBasis?: PromotionTierBasis;
  readonly tierScope?: PromotionTierScope;
  readonly targetType?: PromotionTargetType;
  readonly giftMode?: PromotionGiftMode;
  readonly buyGetPolicy?: PromotionBuyGetPolicy;
  readonly buyQuantity?: number;
  readonly giftQuantity?: number;
  readonly groups: PromotionGroup[];
  readonly condition?: PromotionCondition;
  readonly createdBy: string;
  readonly createdAt?: Date;
  readonly updatedAt?: Date;

  private constructor(props: PromotionProgramProps) {
    this.id = props.id;
    this.organizationId = props.organizationId;
    this.code = props.code;
    this.name = props.name;
    this.description = props.description;
    this.type = props.type;
    this.status = props.status;
    this.priority = props.priority;
    this.applyTo = props.applyTo;
    this.birthdayMatch = props.birthdayMatch;
    this.birthdayBeforeDays = props.birthdayBeforeDays;
    this.birthdayAfterDays = props.birthdayAfterDays;
    this.cardTierId = props.cardTierId;
    this.customerGroupIds = props.customerGroupIds;
    this.startDate = props.startDate;
    this.endDate = props.endDate;
    this.daysOfWeek = props.daysOfWeek;
    this.startTime = props.startTime;
    this.endTime = props.endTime;
    this.autoApply = props.autoApply;
    this.branchIds = props.branchIds;
    this.invoiceScope = props.invoiceScope;
    this.accruePoints = props.accruePoints;
    this.discountMode = props.discountMode;
    this.discountValue = props.discountValue;
    this.maxDiscountAmount = props.maxDiscountAmount;
    this.tierBasis = props.tierBasis;
    this.tierScope = props.tierScope;
    this.targetType = props.targetType;
    this.giftMode = props.giftMode;
    this.buyGetPolicy = props.buyGetPolicy;
    this.buyQuantity = props.buyQuantity;
    this.giftQuantity = props.giftQuantity;
    this.groups = props.groups;
    this.condition = props.condition;
    this.createdBy = props.createdBy;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;

    // `readonly` is a compile-time-only guarantee in TypeScript; freeze so
    // "immutable after create" also holds at runtime.
    Object.freeze(this);
  }

  static create(props: PromotionProgramProps): PromotionProgram {
    const issues = validate(props);
    if (issues.length > 0) {
      throw new DomainValidationError(issues);
    }
    return new PromotionProgram(props);
  }

  /** Snapshot back into constructor props — the basis for "edit = re-validate with merged props" (no public setters). */
  toProps(): PromotionProgramProps {
    return {
      id: this.id,
      organizationId: this.organizationId,
      code: this.code,
      name: this.name,
      description: this.description,
      type: this.type,
      status: this.status,
      priority: this.priority,
      applyTo: this.applyTo,
      birthdayMatch: this.birthdayMatch,
      birthdayBeforeDays: this.birthdayBeforeDays,
      birthdayAfterDays: this.birthdayAfterDays,
      cardTierId: this.cardTierId,
      customerGroupIds: this.customerGroupIds,
      startDate: this.startDate,
      endDate: this.endDate,
      daysOfWeek: this.daysOfWeek,
      startTime: this.startTime,
      endTime: this.endTime,
      autoApply: this.autoApply,
      branchIds: this.branchIds,
      invoiceScope: this.invoiceScope,
      accruePoints: this.accruePoints,
      discountMode: this.discountMode,
      discountValue: this.discountValue,
      maxDiscountAmount: this.maxDiscountAmount,
      tierBasis: this.tierBasis,
      tierScope: this.tierScope,
      targetType: this.targetType,
      giftMode: this.giftMode,
      buyGetPolicy: this.buyGetPolicy,
      buyQuantity: this.buyQuantity,
      giftQuantity: this.giftQuantity,
      groups: this.groups,
      condition: this.condition,
      createdBy: this.createdBy,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }
}
