import { ReportTableColumn, ReportTableColumnGroup, ReportTableColumnLabel } from "./report-column.constant";
import { ReportColumnConfig } from "./report.interface";

export const ReportDailySalesSummaryRegistry: ReportColumnConfig[] = [
  {
    column: ReportTableColumn.DATE,
    label: ReportTableColumnLabel[ReportTableColumn.DATE],
    order: 1,
    visible: true,
    fixed: true,
    number: 0,
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_TOTAL,
    label: ReportTableColumnLabel[ReportTableColumn.REVENUE_TOTAL],
    order: 2,
    visible: true,
    fixed: false,
    number: 1,
    formulaDisplay: '(3)+(4)-(5)-(14)',
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_GOODS,
    label: ReportTableColumnLabel[ReportTableColumn.REVENUE_GOODS],
    order: 3,
    visible: true,
    fixed: false,
    number: 3,
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_FEE,
    label: ReportTableColumnLabel[ReportTableColumn.REVENUE_FEE],
    order: 4,
    visible: true,
    fixed: false,
    number: 4,
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_PROMOTION,
    label: ReportTableColumnLabel[ReportTableColumn.REVENUE_PROMOTION],
    order: 5,
    visible: true,
    fixed: false,
    number: 5,
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_DISCOUNT_POINT,
    label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_POINT],
    order: 6,
    visible: true,
    fixed: false,
    number: 14,
  },
  {
    column: ReportTableColumn.REVENUE_DISCOUNT_RATE,
    label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_RATE],
    order: 7,
    visible: true,
    fixed: false,
    group: ReportTableColumnGroup.REVENUE,
    number: 6,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_CASH,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_CASH],
    order: 8,
    visible: true,
    fixed: false,
    number: 7,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_AMEX_DEBIT,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX_DEBIT],
    order: 9,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_AMEX,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX],
    order: 10,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_ATM,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_ATM],
    order: 11,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_TRANSFER,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_TRANSFER],
    order: 12,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_DINERS,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DINERS],
    order: 13,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_DISCOVER,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DISCOVER],
    order: 14,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_JCB,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_JCB],
    order: 15,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_MASTERCARD_DEBIT,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD_DEBIT],
    order: 16,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_MASTERCARD,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD],
    order: 17,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_QR_TECHCOMBANK,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_QR_TECHCOMBANK],
    order: 18,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_UNIONPAY,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_UNIONPAY],
    order: 19,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_VISA_DEBIT,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA_DEBIT],
    order: 20,
    visible: true,
    fixed: false,
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_VISA,
    label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA],
    order: 21,
    visible: true,
    fixed: false,
  },
  {
    column: ReportTableColumn.NET_REVENUE,
    label: ReportTableColumnLabel[ReportTableColumn.NET_REVENUE],
    order: 22,
    visible: true,
    fixed: false,
    number: 13,
    formulaDisplay: '(1)-(11)-(12)',
  },
];