import { REPORT_CATEGORY } from "./report-category.constant";
import { REPORT_TYPE_CASH_FUND, REPORT_TYPE_DEBTS, REPORT_TYPE_INVENTORY, REPORT_TYPE_MULTI_CHANNEL_SALES, REPORT_TYPE_PROFIT, REPORT_TYPE_PURCHASES, REPORT_TYPE_SALES } from "./report-type.constant";

export const branchReport = {
    [REPORT_CATEGORY.SALES]: Object.values(REPORT_TYPE_SALES),
    [REPORT_CATEGORY.MULTI_CHANNEL_SALES]: Object.values(REPORT_TYPE_MULTI_CHANNEL_SALES),
    [REPORT_CATEGORY.PURCHASES]: Object.values(REPORT_TYPE_PURCHASES),
    [REPORT_CATEGORY.INVENTORY]: Object.values(REPORT_TYPE_INVENTORY),
    [REPORT_CATEGORY.DEBTS]: Object.values(REPORT_TYPE_DEBTS),
    [REPORT_CATEGORY.CASH_FUND]: Object.values(REPORT_TYPE_CASH_FUND),
    [REPORT_CATEGORY.PROFIT]: Object.values(REPORT_TYPE_PROFIT).filter(e => e !== REPORT_TYPE_PROFIT.BUSINESS_RESULTS_BY_BRANCH),
};

export const chainReport = {
    [REPORT_CATEGORY.SALES]: Object.values(REPORT_TYPE_SALES),
    [REPORT_CATEGORY.MULTI_CHANNEL_SALES]: Object.values(REPORT_TYPE_MULTI_CHANNEL_SALES),
    [REPORT_CATEGORY.PURCHASES]: Object.values(REPORT_TYPE_PURCHASES),
    [REPORT_CATEGORY.INVENTORY]: Object.values(REPORT_TYPE_INVENTORY),
    [REPORT_CATEGORY.DEBTS]: Object.values(REPORT_TYPE_DEBTS),
    [REPORT_CATEGORY.CASH_FUND]: Object.values(REPORT_TYPE_CASH_FUND),
    [REPORT_CATEGORY.PROFIT]: Object.values(REPORT_TYPE_PROFIT)
}