import { DocCounterpartyKind } from "./counterparty-kind";

export enum StockMovementType {
  SALE_ISSUE = "SALE_ISSUE",
  RETURN_IN = "RETURN_IN",
  EXCHANGE_IN = "EXCHANGE_IN",
  EXCHANGE_OUT = "EXCHANGE_OUT",
  TRANSFER_IN = "TRANSFER_IN",
  TRANSFER_OUT = "TRANSFER_OUT",
  ADJUSTMENT_INCREASE = "ADJUSTMENT_INCREASE",
  ADJUSTMENT_DECREASE = "ADJUSTMENT_DECREASE",
  PURCHASE_RECEIPT = "PURCHASE_RECEIPT",
  GOODS_ISSUE = "GOODS_ISSUE",
}

export enum TransferStatus {
  DRAFT = "DRAFT",
  APPROVED = "APPROVED",
  POSTED = "POSTED",
  CANCELLED = "CANCELLED",
}

export enum PurchaseOrderStatus {
  DRAFT = "DRAFT",
  APPROVED = "APPROVED",
  RECEIVING = "RECEIVING",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}

export enum GoodsIssueStatus {
  DRAFT = "DRAFT",
  APPROVED = "APPROVED",
  POSTED = "POSTED",
  CANCELLED = "CANCELLED",
}

export enum GoodsIssuePurpose {
  OTHER = "OTHER",
  SALE = "SALE",
  TRANSFER_OUT = "TRANSFER_OUT",
  DISPOSAL = "DISPOSAL",
  /** Auto-generated by a stock-take "Xử lý" for shortage (chênh lệch thiếu). */
  STOCK_TAKE = "STOCK_TAKE",
}

export enum GoodsIssueReferenceType {
  STOCK_TAKE = "STOCK_TAKE",
  TRANSFER_ORDER = "TRANSFER_ORDER",
}

export enum IssueReasonPurpose {
  OTHER = "OTHER",
  DISPOSAL = "DISPOSAL",
}

export enum StockTakeStatus {
  DRAFT = "DRAFT",
  POSTED = "POSTED",
  CANCELLED = "CANCELLED",
}

export enum TransferOrderStatus {
  DRAFT = "DRAFT",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum GoodsReceiptStatus {
  DRAFT = "DRAFT",
  POSTED = "POSTED",
  CANCELLED = "CANCELLED",
  REVERSED = "REVERSED",
}

export enum GoodsReceiptPurpose {
  PURCHASE = "PURCHASE",
  OTHER = "OTHER",
  TRANSFER_IN = "TRANSFER_IN",
  /** Auto-generated by a stock-take "Xử lý" for surplus (chênh lệch thừa). */
  STOCK_TAKE = "STOCK_TAKE",
}

export enum GoodsReceiptReferenceType {
  PURCHASE_ORDER = "PURCHASE_ORDER",
  STOCK_TRANSFER = "STOCK_TRANSFER",
  STOCK_TAKE = "STOCK_TAKE",
}

export type { Product } from "./product";

export { StockStateFilter } from "./stock-by-location";
export type {
  StockByLocationProvider,
  StockByLocationItem,
  StockByLocationStorageRef,
  StockByLocationBranchRef,
  StockByLocationLocationRef,
  StockByLocationMeta,
  StockByLocationResponse,
} from "./stock-by-location";

export * from "./import-excel";
export * from "./item-labels";
export * from "./counterparty-kind";

export enum ImportJobStatus {
  PENDING = "PENDING",
  VALIDATING = "VALIDATING",
  VALIDATED = "VALIDATED",
  IMPORTING = "IMPORTING",
  COMMITTING = "COMMITTING",
  COMMITTED = "COMMITTED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum LocationType {
  SHELF = "SHELF",
  RACK = "RACK",
  BIN = "BIN",
  ZONE = "ZONE",
}

export const LOCATION_TYPE_LABEL: Record<LocationType, string> = {
  [LocationType.SHELF]: "Kệ",
  [LocationType.RACK]: "Giá",
  [LocationType.BIN]: "Thùng",
  [LocationType.ZONE]: "Khu vực",
};

export * from "./temp-warehouse";

import { TempWarehouseDirection } from "./temp-warehouse";

export enum TempWarehouseTransferKind {
  FULL = "FULL",
  PARTIAL = "PARTIAL",
}

export interface TempWarehouseTransferRequestedPayload {
  sessionId: string;
  organizationId: string;
  branchId: string;
  direction: TempWarehouseDirection;
  sourceLocationId: string;
  destinationLocationId: string;
  sourceBranchId: string;
  destinationBranchId: string;
  lines: {
    tempWarehouseLineId: string;
    itemId: string;
    quantity: number;
    sourceLocationId?: string;
  }[];
  actor: {
    userId: string;
    organizationId: string;
    branchId?: string;
    roles: string[];
  };
  requestedAt: string;
  /**
   * Undefined or FULL = published by closeSession(CREATE_TRANSFERS) — consumer updates session-level transferW2sId/S2WId.
   * PARTIAL = published by transferLines — consumer flips the listed lines to TRANSFERRED and stores transferId per line; session-level fields untouched.
   */
  kind?: TempWarehouseTransferKind;
  notes?: string;
}

/**
 * Published by checkout for every posted (non-draft) invoice. The temp-warehouse
 * fulfillment consumer matches each line against ACTIVE warehouse_to_showroom
 * temp-warehouse lines (FIFO), splits/consumes them, and posts a warehouse ->
 * showroom transfer tied to the invoice. eventId is the invoiceId (deterministic)
 * so replays are no-ops; the consumer no-ops when there is no ACTIVE session or
 * no staged line for the item.
 */
export interface TempWarehouseInvoiceFulfillRequestedPayload {
  organizationId: string;
  branchId: string;
  invoiceId: string;
  invoiceNumber: string;
  actor: {
    userId: string;
    organizationId: string;
    branchId?: string;
    roles: string[];
  };
  lines: { itemId: string; quantity: number }[];
}

export interface Provider {
  id: string;
  organizationId: string;
  code: string;
  name: string;
  email?: string;
  phone?: string;
  notes?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface Item {
  id: string;
  organizationId: string;
  code: string;
  name: string;
  description?: string;
  unit: string;
  category?: string;
  isActive: boolean;
  purchasePrice: number;
  sellingPrice: number;
  providerId: string;
  /** Present on admin list rows when joined from the linked provider. */
  providerName?: string;
  providerCode?: string;
  /** FK to products — null for legacy items without a parent product. */
  productId?: string;
  /** Denormalized display label for variant attributes (e.g. "39 · Nâu"). */
  variantLabel?: string;
  /** Present on list rows when joined from the linked product. */
  productName?: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface Storage {
  id: string;
  organizationId: string;
  branchId: string;
  name: string;
  isMainStorage: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface Showroom {
  id: string;
  organizationId: string;
  branchId: string;
  storageId: string;
  name: string;
  isMainShowroom: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface Location {
  id: string;
  organizationId: string;
  branchId: string;
  storageId: string;
  code: string;
  name: string;
  type: LocationType;
  description?: string | null;
  isActive: boolean;
  isUnassigned: boolean;
  hasItems?: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface StorageManagerAssignment {
  id: string;
  userId: string;
  branchId: string;
  storageId: string;
  organizationId: string;
  assignedAt: string;
  assignedBy: string;
}

export interface StockBalance {
  id: string;
  organizationId: string;
  branchId: string;
  itemId: string;
  locationId: string;
  quantity: number;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  /** Present on admin list rows when joined from the linked item. */
  itemName?: string;
  itemCode?: string;
  /** Category, unit, and description summary from the linked item. */
  itemVariants?: string;
  /** Name of the parent product (via item.product). Empty for legacy items. */
  productName?: string;
  /** Variant attribute label (e.g. "39 · Nâu"), falls back to category/unit/desc for legacy items. */
  variantLabel?: string;
}

export interface StockLedgerEntry {
  id: string;
  organizationId: string;
  branchId: string;
  itemId: string;
  locationId: string;
  movementType: StockMovementType;
  quantity: number;
  referenceId: string;
  referenceType: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface StockTransfer {
  id: string;
  organizationId: string;
  branchId?: string;
  fromLocationId: string;
  toLocationId: string;
  status: TransferStatus;
  lines: StockTransferLine[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface StockTransferLine {
  id: string;
  transferId: string;
  itemId: string;
  quantity: number;
}

export interface StockAdjustment {
  id: string;
  organizationId: string;
  branchId: string;
  locationId: string;
  status: TransferStatus;
  reason: string;
  lines: StockAdjustmentLine[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface StockAdjustmentLine {
  id: string;
  adjustmentId: string;
  itemId: string;
  quantityChange: number;
}

export interface ImportJob {
  id: string;
  organizationId: string;
  branchId: string;
  status: ImportJobStatus;
  fileName: string;
  totalRows: number;
  processedRows: number;
  errorRows: number;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface ImportJobRow {
  id: string;
  importJobId: string;
  rowNumber: number;
  data: Record<string, unknown>;
  error?: string;
  status: "PENDING" | "SUCCESS" | "ERROR";
}

export interface PurchaseOrderLine {
  id: string;
  purchaseOrderId: string;
  itemId: string;
  orderedQuantity: number;
  receivedQuantity: number;
  unitPrice: number;
  notes?: string;
}

export interface PurchaseOrder {
  id: string;
  organizationId: string;
  branchId?: string;
  documentNumber?: string;
  providerId: string;
  locationId: string;
  status: PurchaseOrderStatus;
  expectedDate?: string;
  notes?: string;
  approvedBy?: string;
  approvedAt?: string;
  lines: PurchaseOrderLine[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface GoodsIssueLine {
  id: string;
  goodsIssueId: string;
  itemId: string;
  quantity: number;
  notes?: string;
}

export interface GoodsIssue {
  id: string;
  organizationId: string;
  branchId?: string;
  documentNumber?: string;
  locationId: string;
  reason: string;
  status: GoodsIssueStatus;
  notes?: string;
  approvedBy?: string;
  approvedAt?: string;
  postedBy?: string;
  postedAt?: string;
  lines: GoodsIssueLine[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

/**
 * A DRAFT transfer order that the active branch (as source) can issue stock
 * from — the row shape returned by GET /inventory/transfer-orders/issuable and
 * rendered in the "Chọn lệnh điều chuyển" picker on the goods-issue form.
 */
export interface IssuableTransferOrderListItem {
  id: string;
  documentNumber: string;
  /** "Ngày" — requestedDate when set, otherwise the creation date. ISO string. */
  requestedDate: string | null;
  /** "Lý do" — the transfer order notes. */
  notes: string | null;
  destinationBranchId: string;
  /** "Điều chuyển đến" — resolved destination branch name, inlined per row. */
  destinationBranchName: string;
  status: TransferOrderStatus;
}

/**
 * One row in the "Chọn chứng từ xuất kho điều chuyển" import picker — an
 * IN_PROGRESS transfer order whose destination branch is the active branch.
 */
export interface ImportableTransferOrderListItem {
  id: string;
  documentNumber: string;
  /** "Ngày" — requestedDate when set, otherwise the creation date. ISO string. */
  requestedDate: string | null;
  notes: string | null;
  sourceBranchId: string;
  /** "Điều chuyển từ" — resolved source branch name, inlined per row. */
  sourceBranchName: string;
  exportGoodsIssueId: string | null;
  importGoodsReceiptId: string | null;
  /** "Số chứng từ" — the export goods-issue (XK) document number. */
  exportGoodsIssueDocumentNumber: string | null;
  /** "Đối tượng" — counterparty selected on the export goods issue. */
  counterpartyName: string | null;
  /** "Tổng thành tiền" — sum of the export goods-issue line totals. */
  totalAmount: number;
  lines: Array<{
    id: string;
    itemId: string;
    itemCode: string;
    itemName: string;
    unit: string;
    storageName: string | null;
    locationCode: string | null;
    locationName: string | null;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
    notes: string | null;
  }>;
  status: TransferOrderStatus;
}

/** One edited goods-issue line submitted when exporting from the form. */
export interface ExportTransferOrderLine {
  itemId: string;
  locationId: string;
  quantity: number;
  unitPrice?: number;
  notes?: string;
}

/**
 * Optional body of POST /inventory/transfer-orders/:id/export. When `lines` is
 * present the export uses the (possibly edited) form lines instead of deriving
 * them from the transfer order; omitting it preserves the legacy derive path.
 */
export interface ExportTransferOrderRequest {
  lines?: ExportTransferOrderLine[];
  reason?: string;
  notes?: string;
  /** Đối tượng (counterparty provider) selected on the goods-issue form. */
  providerId?: string;
  /** Đối tượng kind selected on the goods-issue form. */
  counterpartyKind?: DocCounterpartyKind;
  /** Id of the provider / customer / employee, per counterpartyKind. */
  counterpartyId?: string;
  /** Người giao (free-text deliverer name). */
  deliverer?: string;
  /** Tham chiếu — FE-supplied reference codes (e.g. the source LDC number). */
  references?: string[];
  /** User-entered issue date+time (ISO); falls back to createdAt when omitted. */
  occurredAt?: string;
}

/** One received goods-receipt line submitted when importing from the form. */
export interface ImportTransferOrderLine {
  itemId: string;
  /** Destination bin (Vị trí) the line is received into. */
  locationId: string;
  quantity: number;
  unitPrice?: number;
  note?: string;
}

/**
 * Optional body of POST /inventory/transfer-orders/:id/import. When `lines` is
 * present the receipt uses the form's per-line Kho/Vị trí; otherwise it derives
 * every line into the destination storage's default bin (legacy). The header
 * fields round-trip onto the spawned receipt (mirrors ExportTransferOrderRequest).
 */
export interface ImportTransferOrderRequest {
  /** Per-line received Kho/Vị trí chosen on the form. */
  lines?: ImportTransferOrderLine[];
  /** Kho nhận — fallback destination warehouse when `lines` is omitted. */
  destinationStorageId?: string;
  /** Đối tượng (counterparty provider). */
  providerId?: string;
  /** Người giao (free-text deliverer name). */
  deliverer?: string;
  /** Tham chiếu — FE-supplied reference codes. */
  references?: string[];
  /** User-entered receive date+time (ISO); falls back to now when omitted. */
  occurredAt?: string;
}
