import { ApiProperty } from '@nestjs/swagger';
import { MediaStatus } from '../media-object.entity';

export class UploadPolicyResponseDto {
  @ApiProperty({ description: 'Absolute URL the browser POSTs the multipart/form-data upload to.' })
  url: string;

  @ApiProperty({
    description:
      'Form fields the browser must send verbatim alongside the file, generated by createPresignedPost.',
    type: 'object',
    additionalProperties: { type: 'string' },
  })
  fields: Record<string, string>;
}

export class RequestMediaUploadResponseDto {
  @ApiProperty({ format: 'uuid' })
  mediaId: string;

  @ApiProperty({ type: UploadPolicyResponseDto })
  upload: UploadPolicyResponseDto;

  @ApiProperty({ description: 'When the upload ticket expires (10 minutes from issuance).', format: 'date-time' })
  expiresAt: string;
}

export class CompleteMediaUploadResponseDto {
  @ApiProperty({ format: 'uuid' })
  mediaId: string;

  @ApiProperty({ enum: MediaStatus, enumName: 'MediaStatus' })
  status: MediaStatus;

  @ApiProperty()
  fileName: string;

  @ApiProperty()
  contentType: string;

  @ApiProperty({ description: 'Size in bytes.' })
  size: number;
}
