import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1777056744410 implements MigrationInterface {
    name = 'InitSchema1777056744410'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "salesman_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" uuid NOT NULL, CONSTRAINT "UQ_47db4d3fa8d304b08167b6eb268" UNIQUE ("user_id", "branch_id"), CONSTRAINT "PK_f54d278edae553ca48889033cc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_manager_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" uuid NOT NULL, CONSTRAINT "UQ_0890e445639c0d54ffdebb4eed7" UNIQUE ("user_id", "branch_id"), CONSTRAINT "PK_8a2492cea0982c32c71aead8b4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."registration_requests_type_enum" AS ENUM('ORGANIZATION', 'BRANCH')`);
        await queryRunner.query(`CREATE TYPE "public"."registration_requests_status_enum" AS ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'RESUBMITTED')`);
        await queryRunner.query(`CREATE TABLE "registration_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "type" "public"."registration_requests_type_enum" NOT NULL, "request_data" jsonb NOT NULL, "status" "public"."registration_requests_status_enum" NOT NULL DEFAULT 'PENDING_APPROVAL', "reviewed_by" uuid, "reviewed_at" TIMESTAMP WITH TIME ZONE, "rejection_reason" character varying, CONSTRAINT "PK_75e49f863f30250e82ab8638eaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pos_session_reconciliations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "session_id" uuid NOT NULL, "expected_cash" numeric(18,2) NOT NULL DEFAULT '0', "actual_cash" numeric(18,2) NOT NULL DEFAULT '0', "variance" numeric(18,2) NOT NULL DEFAULT '0', "variance_approved" boolean NOT NULL DEFAULT false, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "notes" text, CONSTRAINT "PK_9fd9b96e8f355df103697a911b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a876464727131dd5bfc36969f0" ON "pos_session_reconciliations" ("organization_id", "session_id") `);
        await queryRunner.query(`CREATE TABLE "pos_sale_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "sale_id" uuid NOT NULL, "item_id" uuid NOT NULL, "location_id" uuid NOT NULL, "quantity" numeric(18,2) NOT NULL, "unit_price" numeric(18,2) NOT NULL, "line_total" numeric(18,2) NOT NULL, "tax_amount" numeric(18,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_cb96fc4812688afd69d1f6f9d5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbd5bec7069236e5b32f629d74" ON "pos_sale_lines" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23e4ee5117211792abb4e14793" ON "pos_sale_lines" ("sale_id") `);
        await queryRunner.query(`CREATE TYPE "public"."pos_payments_method_enum" AS ENUM('CASH', 'CARD', 'CREDIT', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "pos_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "sale_id" uuid NOT NULL, "method" "public"."pos_payments_method_enum" NOT NULL, "amount" numeric(18,2) NOT NULL, "reference" character varying(255), CONSTRAINT "PK_6afc9afb629169943944acf6d68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b44d3e7e99b20e38b6025720f" ON "pos_payments" ("sale_id") `);
        await queryRunner.query(`CREATE TYPE "public"."pos_sales_status_enum" AS ENUM('COMPLETED', 'RETURNED', 'PARTIALLY_RETURNED')`);
        await queryRunner.query(`CREATE TABLE "pos_sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying(100) NOT NULL, "session_id" uuid NOT NULL, "customer_id" uuid, "subtotal" numeric(18,2) NOT NULL DEFAULT '0', "tax_amount" numeric(18,2) NOT NULL DEFAULT '0', "total_amount" numeric(18,2) NOT NULL DEFAULT '0', "status" "public"."pos_sales_status_enum" NOT NULL DEFAULT 'COMPLETED', "sale_date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_ae373d79543e016f6028c0061aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbe9d25407df6ece81af558efa" ON "pos_sales" ("organization_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1cd545f0817b4fd7e4deead10" ON "pos_sales" ("organization_id", "branch_id", "sale_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7de8ee191320f8396f0c7e1231" ON "pos_sales" ("organization_id", "session_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_sale_doc_number" ON "pos_sales" ("organization_id", "document_number") `);
        await queryRunner.query(`CREATE TABLE "pos_return_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "return_id" uuid NOT NULL, "original_sale_line_id" uuid NOT NULL, "item_id" uuid NOT NULL, "location_id" uuid NOT NULL, "quantity" numeric(18,2) NOT NULL, "unit_price" numeric(18,2) NOT NULL, "line_total" numeric(18,2) NOT NULL, CONSTRAINT "PK_9aa388a8c393588a432bb2b2c16" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_edba47a74e2e1b4147463774e5" ON "pos_return_lines" ("original_sale_line_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9704f89f96a3be314504fb4acd" ON "pos_return_lines" ("return_id") `);
        await queryRunner.query(`CREATE TABLE "pos_returns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying(100) NOT NULL, "original_sale_id" uuid NOT NULL, "session_id" uuid NOT NULL, "subtotal" numeric(18,2) NOT NULL DEFAULT '0', "tax_amount" numeric(18,2) NOT NULL DEFAULT '0', "total_amount" numeric(18,2) NOT NULL DEFAULT '0', "reason" text NOT NULL, "return_date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_8d17e9c0dff35fe344cd73f6e7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a09d181d39d5a79e92435065e" ON "pos_returns" ("organization_id", "branch_id", "return_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_43101b2c2754f142b37a8f26b5" ON "pos_returns" ("organization_id", "session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c976002885a583ebfda7a9a724" ON "pos_returns" ("organization_id", "original_sale_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_return_doc_number" ON "pos_returns" ("organization_id", "document_number") `);
        await queryRunner.query(`CREATE TYPE "public"."pos_sessions_status_enum" AS ENUM('OPEN', 'ACTIVE_SALES', 'CLOSING', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "pos_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "terminal_id" uuid, "status" "public"."pos_sessions_status_enum" NOT NULL DEFAULT 'OPEN', "opened_by" uuid NOT NULL, "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL, "closed_by" uuid, "closed_at" TIMESTAMP WITH TIME ZONE, "opening_cash_amount" numeric(18,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_ea6a8d8a95103f03518a0f72c45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71834fad2b491b8e5785356bca" ON "pos_sessions" ("organization_id", "opened_by", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b5dfb942739d0c904d5dd04fb" ON "pos_sessions" ("organization_id", "branch_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."organizations_status_enum" AS ENUM('ACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "name" character varying NOT NULL, "contact_email" character varying NOT NULL, "contact_phone" character varying, "main_branch_id" uuid, "status" "public"."organizations_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "UQ_9b7ca6d30b94fef571cff876884" UNIQUE ("name"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfer_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "item_id" uuid NOT NULL, "quantity" numeric NOT NULL, "notes" character varying, CONSTRAINT "PK_471b427d94a3f10ca3bcd9de9ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_transfers_status_enum" AS ENUM('DRAFT', 'APPROVED', 'POSTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying, "source_location_id" uuid NOT NULL, "destination_location_id" uuid NOT NULL, "source_branch_id" uuid NOT NULL, "destination_branch_id" uuid NOT NULL, "status" "public"."stock_transfers_status_enum" NOT NULL DEFAULT 'DRAFT', "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "posted_by" uuid, "posted_at" TIMESTAMP WITH TIME ZONE, "notes" character varying, CONSTRAINT "UQ_1bb5e7b35ce2131ca7c5dd7465c" UNIQUE ("document_number"), CONSTRAINT "PK_ef738a3a4a578c7f1802c1bb50a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40e33edcfd30b61d159b0e0d02" ON "stock_transfers" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."branches_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "name" character varying NOT NULL, "address" character varying, "phone" character varying, "email" character varying, "status" "public"."branches_status_enum" NOT NULL DEFAULT 'ACTIVE', "is_main_branch" boolean NOT NULL DEFAULT false, "parent_branch_id" uuid, CONSTRAINT "UQ_07f6271bbdf388a0b8050f4d907" UNIQUE ("organization_id", "name"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "storages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "name" character varying NOT NULL, "is_main_storage" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_7e4f519ea8f3cd94f01eae91877" UNIQUE ("branch_id", "name"), CONSTRAINT "PK_2f2d2fae6dc214f7f3ec52189ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "storage_manager_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "storage_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" uuid NOT NULL, CONSTRAINT "UQ_983b00d5ed2a9ba327975a61767" UNIQUE ("user_id", "storage_id"), CONSTRAINT "PK_6d1f0b1e52606f2885d78e7292e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "showrooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "name" character varying NOT NULL, "storage_id" uuid NOT NULL, "is_main_showroom" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_19d47c8c82c9c97830812609969" UNIQUE ("branch_id", "name"), CONSTRAINT "PK_b2ebdaf63656a94336aa9a336a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."locations_type_enum" AS ENUM('SHELF', 'RACK', 'BIN', 'ZONE')`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "storage_id" uuid NOT NULL, "type" "public"."locations_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e2793cc845fc2e9e9d6ffcd7c4d" UNIQUE ("storage_id", "code"), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "unit" character varying NOT NULL, "category" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_72337e6413e97c8b8fc2e1aaabf" UNIQUE ("organization_id", "code"), CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_ledger_entries_movement_type_enum" AS ENUM('SALE_ISSUE', 'RETURN_IN', 'EXCHANGE_IN', 'EXCHANGE_OUT', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT_INCREASE', 'ADJUSTMENT_DECREASE', 'PURCHASE_RECEIPT')`);
        await queryRunner.query(`CREATE TABLE "stock_ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "item_id" uuid NOT NULL, "location_id" uuid NOT NULL, "movement_type" "public"."stock_ledger_entries_movement_type_enum" NOT NULL, "quantity" numeric NOT NULL, "reference_type" character varying NOT NULL, "reference_id" uuid NOT NULL, "notes" character varying, "posted_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_ce332a237ab9d7e46edd9078657" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4a098f2865a3fb895a6fba599" ON "stock_ledger_entries" ("organization_id", "branch_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_52a1358fb6c46cf0301645b05f" ON "stock_ledger_entries" ("organization_id", "item_id", "location_id") `);
        await queryRunner.query(`CREATE TABLE "stock_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "item_id" uuid NOT NULL, "location_id" uuid NOT NULL, "quantity" numeric NOT NULL DEFAULT '0', "last_movement_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_cdc68ff0affee9f98018ccb74e4" UNIQUE ("organization_id", "item_id", "location_id"), CONSTRAINT "PK_4c0d249ce58f9a559eb7df31b23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f519dbfad591ac0b9fe2e66d31" ON "stock_balances" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_import_job_rows_status_enum" AS ENUM('VALID', 'ERROR', 'COMMITTED')`);
        await queryRunner.query(`CREATE TABLE "inventory_import_job_rows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "row_number" integer NOT NULL, "raw_data" jsonb NOT NULL, "status" "public"."inventory_import_job_rows_status_enum" NOT NULL, "error_messages" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f56fa46a4b4165ab40c53b54eed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5234bd936f5b6a4d59de59e405" ON "inventory_import_job_rows" ("job_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_import_jobs_type_enum" AS ENUM('ITEMS', 'OPENING_BALANCES', 'ADJUSTMENTS')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_import_jobs_status_enum" AS ENUM('PENDING', 'VALIDATING', 'VALIDATED', 'IMPORTING', 'COMMITTING', 'COMMITTED', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "inventory_import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "type" "public"."inventory_import_jobs_type_enum" NOT NULL, "file_name" character varying NOT NULL, "file_checksum" character varying NOT NULL, "idempotency_key" character varying NOT NULL, "status" "public"."inventory_import_jobs_status_enum" NOT NULL DEFAULT 'VALIDATING', "total_rows" integer NOT NULL DEFAULT '0', "valid_rows" integer NOT NULL DEFAULT '0', "error_rows" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_479ca94cb28c1888acb763bc136" UNIQUE ("organization_id", "type", "idempotency_key"), CONSTRAINT "PK_bee1ba04c027bbffe7e610adcbc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0b97056b2b733bbd7baa47536" ON "inventory_import_jobs" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TABLE "stock_adjustment_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adjustment_id" uuid NOT NULL, "item_id" uuid NOT NULL, "quantity" numeric NOT NULL, "notes" character varying, CONSTRAINT "PK_18ca8b2aae693457bf8f1f24e2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_adjustments_status_enum" AS ENUM('DRAFT', 'PENDING_APPROVAL', 'POSTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "stock_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying, "location_id" uuid NOT NULL, "reason_code" character varying NOT NULL, "reason_description" character varying, "status" "public"."stock_adjustments_status_enum" NOT NULL DEFAULT 'DRAFT', "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "posted_by" uuid, "posted_at" TIMESTAMP WITH TIME ZONE, "notes" character varying, CONSTRAINT "UQ_3364ca02be7ba1cdaa71f5c3b4e" UNIQUE ("document_number"), CONSTRAINT "PK_7dc03d92f242dd489d33b80d063" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f489267a95d9ef3f350904e36" ON "stock_adjustments" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."document_number_rules_document_type_enum" AS ENUM('INVOICE', 'SALE', 'RETURN', 'TRANSFER', 'ADJUSTMENT', 'JOURNAL', 'PAYABLE', 'RECEIVABLE')`);
        await queryRunner.query(`CREATE TYPE "public"."document_number_rules_reset_policy_enum" AS ENUM('NEVER', 'DAILY', 'MONTHLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "document_number_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_type" "public"."document_number_rules_document_type_enum" NOT NULL, "prefix" character varying(50) NOT NULL, "suffix" character varying(50), "include_date" boolean NOT NULL DEFAULT true, "date_format" character varying(20) NOT NULL DEFAULT 'YYYYMMDD', "sequence_length" smallint NOT NULL DEFAULT '5', "reset_policy" "public"."document_number_rules_reset_policy_enum" NOT NULL DEFAULT 'NEVER', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_active_rule_scope" UNIQUE ("organization_id", "branch_id", "document_type", "is_active"), CONSTRAINT "PK_0d92be44f6a81141d348a52505c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_number_counters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rule_id" uuid NOT NULL, "organization_id" character varying NOT NULL, "branch_id" character varying, "current_value" bigint NOT NULL DEFAULT '0', "reset_key" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_rule_reset_key" UNIQUE ("rule_id", "reset_key"), CONSTRAINT "PK_8ec2652dfc3b9f752991258f473" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customers_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'MERGED')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying, "phone" character varying, "address" character varying, "status" "public"."customers_status_enum" NOT NULL DEFAULT 'ACTIVE', "merged_into_id" uuid, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_customer_org_phone" ON "customers" ("organization_id", "phone") `);
        await queryRunner.query(`CREATE INDEX "idx_customer_org_status" ON "customers" ("organization_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_customer_org_email" ON "customers" ("organization_id", "email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "user_branch_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" uuid NOT NULL, CONSTRAINT "UQ_5c7c7a7d6c4926559c04aac01cb" UNIQUE ("user_id", "branch_id"), CONSTRAINT "PK_4506f2ed3c447a06de04d838b1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_04402eb4cf7be16f6cc5e5f0788" UNIQUE ("email", "organization_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bb49246f460b189312962c62183" UNIQUE ("user_id", "role_id", "organization_id"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(500), "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8bdcf7999d2e71031da1f4869a6" UNIQUE ("organization_id", "name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "UQ_25d24010f53bb80b78e412c9656" UNIQUE ("role_id", "permission_id"), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "description" character varying(500), "module" character varying(100) NOT NULL, CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "receivable_settlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "receivable_id" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "settlement_date" date NOT NULL, "method" character varying(50) NOT NULL, "reference" character varying(255), CONSTRAINT "PK_987ba07f63a2951e3bb7655026c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_receivable_settlement_receivable" ON "receivable_settlements" ("receivable_id") `);
        await queryRunner.query(`CREATE TYPE "public"."receivables_status_enum" AS ENUM('DRAFT', 'POSTED', 'PARTIALLY_SETTLED', 'SETTLED', 'VOIDED', 'WRITTEN_OFF')`);
        await queryRunner.query(`CREATE TABLE "receivables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying(100), "customer_id" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "due_date" date NOT NULL, "status" "public"."receivables_status_enum" NOT NULL DEFAULT 'DRAFT', "account_id" uuid NOT NULL, "settled_amount" numeric(18,2) NOT NULL DEFAULT '0', "posted_at" TIMESTAMP WITH TIME ZONE, "posted_by" uuid, "write_off_reason" text, CONSTRAINT "PK_d77a2c19436083a2039cf06f1ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_receivable_customer" ON "receivables" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_receivable_due_date" ON "receivables" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_receivable_org_branch" ON "receivables" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_receivable_org_status" ON "receivables" ("organization_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_receivable_doc_number" ON "receivables" ("organization_id", "document_number") `);
        await queryRunner.query(`CREATE TABLE "payable_settlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "payable_id" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "settlement_date" date NOT NULL, "method" character varying(50) NOT NULL, "reference" character varying(255), CONSTRAINT "PK_b556e0bbb6226fd2796e36e3188" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payable_settlement_payable" ON "payable_settlements" ("payable_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payables_status_enum" AS ENUM('DRAFT', 'POSTED', 'PARTIALLY_SETTLED', 'SETTLED', 'VOIDED')`);
        await queryRunner.query(`CREATE TABLE "payables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying(100), "vendor_name" character varying(255) NOT NULL, "amount" numeric(18,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "due_date" date NOT NULL, "status" "public"."payables_status_enum" NOT NULL DEFAULT 'DRAFT', "account_id" uuid NOT NULL, "settled_amount" numeric(18,2) NOT NULL DEFAULT '0', "posted_at" TIMESTAMP WITH TIME ZONE, "posted_by" uuid, CONSTRAINT "PK_33adb2ad800095b1f556f01b2c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payable_due_date" ON "payables" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_payable_org_branch" ON "payables" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payable_org_status" ON "payables" ("organization_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_payable_doc_number" ON "payables" ("organization_id", "document_number") `);
        await queryRunner.query(`CREATE TYPE "public"."journal_entries_source_enum" AS ENUM('SALE', 'RETURN', 'EXCHANGE', 'EXPENSE', 'CASH_MOVEMENT', 'MANUAL', 'TRANSFER')`);
        await queryRunner.query(`CREATE TYPE "public"."journal_entries_status_enum" AS ENUM('POSTED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "journal_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "document_number" character varying(100) NOT NULL, "source" "public"."journal_entries_source_enum" NOT NULL, "source_reference_id" uuid, "description" text, "notes" text, "status" "public"."journal_entries_status_enum" NOT NULL DEFAULT 'POSTED', "posted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "posted_by" uuid NOT NULL, "reversed_by_journal_id" uuid, "reversal_of_journal_id" uuid, CONSTRAINT "PK_a70368e64230434457c8d007ab3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_journal_source_ref" ON "journal_entries" ("source_reference_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_posted_at" ON "journal_entries" ("posted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_org_branch" ON "journal_entries" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_org_status" ON "journal_entries" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_org_source" ON "journal_entries" ("organization_id", "source") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_journal_doc_number" ON "journal_entries" ("organization_id", "document_number") `);
        await queryRunner.query(`CREATE TABLE "journal_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "journal_entry_id" uuid NOT NULL, "account_id" uuid NOT NULL, "debit_amount" numeric(18,2) NOT NULL DEFAULT '0', "credit_amount" numeric(18,2) NOT NULL DEFAULT '0', "description" text, "line_order" integer NOT NULL, CONSTRAINT "PK_70cba2da4588cee8921f73ef136" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_journal_line_account" ON "journal_lines" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_line_entry" ON "journal_lines" ("journal_entry_id") `);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('DRAFT', 'APPROVED', 'POSTED')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "description" text NOT NULL, "amount" numeric(18,2) NOT NULL, "account_id" uuid NOT NULL, "payable_id" uuid, "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'DRAFT', "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "posted_at" TIMESTAMP WITH TIME ZONE, "posted_by" uuid, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_expense_account" ON "expenses" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_org_branch" ON "expenses" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_org_status" ON "expenses" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."accounts_type_enum" AS ENUM('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE')`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "code" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "type" "public"."accounts_type_enum" NOT NULL, "parent_account_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_account_parent" ON "accounts" ("parent_account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_account_org_type" ON "accounts" ("organization_id", "type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_account_org_code" ON "accounts" ("organization_id", "code") `);
        await queryRunner.query(`CREATE TABLE "cash_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "name" character varying(200) NOT NULL, "balance" numeric(18,2) NOT NULL DEFAULT '0', "account_id" uuid NOT NULL, CONSTRAINT "PK_c10b1fd07d801b17fb333711b2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_cash_account_ledger" ON "cash_accounts" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_cash_account_org_branch" ON "cash_accounts" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE TYPE "public"."cash_movements_type_enum" AS ENUM('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'ADJUSTMENT')`);
        await queryRunner.query(`CREATE TABLE "cash_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "branch_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "cash_account_id" uuid NOT NULL, "type" "public"."cash_movements_type_enum" NOT NULL, "amount" numeric(18,2) NOT NULL, "reference" character varying(255), "notes" text, CONSTRAINT "PK_25faead19e1ff74153a01604d37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_cash_movement_org_branch" ON "cash_movements" ("organization_id", "branch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_cash_movement_account" ON "cash_movements" ("cash_account_id") `);
        await queryRunner.query(`ALTER TABLE "pos_sale_lines" ADD CONSTRAINT "FK_23e4ee5117211792abb4e14793a" FOREIGN KEY ("sale_id") REFERENCES "pos_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_payments" ADD CONSTRAINT "FK_9b44d3e7e99b20e38b6025720fb" FOREIGN KEY ("sale_id") REFERENCES "pos_sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_return_lines" ADD CONSTRAINT "FK_9704f89f96a3be314504fb4acd3" FOREIGN KEY ("return_id") REFERENCES "pos_returns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" ADD CONSTRAINT "FK_f4133789cec434f02b9b2212a81" FOREIGN KEY ("transfer_id") REFERENCES "stock_transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_3051ed6a712034f521831ede69a" FOREIGN KEY ("parent_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storages" ADD CONSTRAINT "FK_9e2b01f4772d028c622f5bd1192" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showrooms" ADD CONSTRAINT "FK_a2e531ca37e210507a3b7a21b36" FOREIGN KEY ("storage_id") REFERENCES "storages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showrooms" ADD CONSTRAINT "FK_752703721e868416ed17e4cde7f" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_101b1683509841e556e31b31cf2" FOREIGN KEY ("storage_id") REFERENCES "storages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_import_job_rows" ADD CONSTRAINT "FK_3a9e9cbddf8a88cb743f8b22774" FOREIGN KEY ("job_id") REFERENCES "inventory_import_jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_lines" ADD CONSTRAINT "FK_6a00cd7c239351d1ba04faec16b" FOREIGN KEY ("adjustment_id") REFERENCES "stock_adjustments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_number_counters" ADD CONSTRAINT "FK_c33a10cf4a9fad068be3fafe266" FOREIGN KEY ("rule_id") REFERENCES "document_number_rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_f95767fe8a07a6723d2402ef506" FOREIGN KEY ("merged_into_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receivable_settlements" ADD CONSTRAINT "FK_20fb2ed2de374359d355253f97c" FOREIGN KEY ("receivable_id") REFERENCES "receivables"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payable_settlements" ADD CONSTRAINT "FK_4b438b677c69aba826515afefda" FOREIGN KEY ("payable_id") REFERENCES "payables"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_1fd23ae91f0c24764b4e581c72e" FOREIGN KEY ("journal_entry_id") REFERENCES "journal_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_82655922433e50df4fd451d5240" FOREIGN KEY ("parent_account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD CONSTRAINT "FK_6d13c7b23ff93618d55e65100d7" FOREIGN KEY ("cash_account_id") REFERENCES "cash_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP CONSTRAINT "FK_6d13c7b23ff93618d55e65100d7"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_82655922433e50df4fd451d5240"`);
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_1fd23ae91f0c24764b4e581c72e"`);
        await queryRunner.query(`ALTER TABLE "payable_settlements" DROP CONSTRAINT "FK_4b438b677c69aba826515afefda"`);
        await queryRunner.query(`ALTER TABLE "receivable_settlements" DROP CONSTRAINT "FK_20fb2ed2de374359d355253f97c"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_f95767fe8a07a6723d2402ef506"`);
        await queryRunner.query(`ALTER TABLE "document_number_counters" DROP CONSTRAINT "FK_c33a10cf4a9fad068be3fafe266"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_lines" DROP CONSTRAINT "FK_6a00cd7c239351d1ba04faec16b"`);
        await queryRunner.query(`ALTER TABLE "inventory_import_job_rows" DROP CONSTRAINT "FK_3a9e9cbddf8a88cb743f8b22774"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_101b1683509841e556e31b31cf2"`);
        await queryRunner.query(`ALTER TABLE "showrooms" DROP CONSTRAINT "FK_752703721e868416ed17e4cde7f"`);
        await queryRunner.query(`ALTER TABLE "showrooms" DROP CONSTRAINT "FK_a2e531ca37e210507a3b7a21b36"`);
        await queryRunner.query(`ALTER TABLE "storages" DROP CONSTRAINT "FK_9e2b01f4772d028c622f5bd1192"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_3051ed6a712034f521831ede69a"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" DROP CONSTRAINT "FK_f4133789cec434f02b9b2212a81"`);
        await queryRunner.query(`ALTER TABLE "pos_return_lines" DROP CONSTRAINT "FK_9704f89f96a3be314504fb4acd3"`);
        await queryRunner.query(`ALTER TABLE "pos_payments" DROP CONSTRAINT "FK_9b44d3e7e99b20e38b6025720fb"`);
        await queryRunner.query(`ALTER TABLE "pos_sale_lines" DROP CONSTRAINT "FK_23e4ee5117211792abb4e14793a"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_movement_account"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_movement_org_branch"`);
        await queryRunner.query(`DROP TABLE "cash_movements"`);
        await queryRunner.query(`DROP TYPE "public"."cash_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_account_org_branch"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_account_ledger"`);
        await queryRunner.query(`DROP TABLE "cash_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."uq_account_org_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_account_org_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_account_parent"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expense_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expense_org_branch"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expense_account"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_line_entry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_line_account"`);
        await queryRunner.query(`DROP TABLE "journal_lines"`);
        await queryRunner.query(`DROP INDEX "public"."uq_journal_doc_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_org_source"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_org_branch"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_posted_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_source_ref"`);
        await queryRunner.query(`DROP TABLE "journal_entries"`);
        await queryRunner.query(`DROP TYPE "public"."journal_entries_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."journal_entries_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_payable_doc_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payable_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payable_org_branch"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payable_due_date"`);
        await queryRunner.query(`DROP TABLE "payables"`);
        await queryRunner.query(`DROP TYPE "public"."payables_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payable_settlement_payable"`);
        await queryRunner.query(`DROP TABLE "payable_settlements"`);
        await queryRunner.query(`DROP INDEX "public"."uq_receivable_doc_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receivable_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receivable_org_branch"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receivable_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receivable_customer"`);
        await queryRunner.query(`DROP TABLE "receivables"`);
        await queryRunner.query(`DROP TYPE "public"."receivables_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receivable_settlement_receivable"`);
        await queryRunner.query(`DROP TABLE "receivable_settlements"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user_branch_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."uq_customer_org_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_customer_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_customer_org_phone"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_status_enum"`);
        await queryRunner.query(`DROP TABLE "document_number_counters"`);
        await queryRunner.query(`DROP TABLE "document_number_rules"`);
        await queryRunner.query(`DROP TYPE "public"."document_number_rules_reset_policy_enum"`);
        await queryRunner.query(`DROP TYPE "public"."document_number_rules_document_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f489267a95d9ef3f350904e36"`);
        await queryRunner.query(`DROP TABLE "stock_adjustments"`);
        await queryRunner.query(`DROP TYPE "public"."stock_adjustments_status_enum"`);
        await queryRunner.query(`DROP TABLE "stock_adjustment_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0b97056b2b733bbd7baa47536"`);
        await queryRunner.query(`DROP TABLE "inventory_import_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_import_jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_import_jobs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5234bd936f5b6a4d59de59e405"`);
        await queryRunner.query(`DROP TABLE "inventory_import_job_rows"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_import_job_rows_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f519dbfad591ac0b9fe2e66d31"`);
        await queryRunner.query(`DROP TABLE "stock_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52a1358fb6c46cf0301645b05f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4a098f2865a3fb895a6fba599"`);
        await queryRunner.query(`DROP TABLE "stock_ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."stock_ledger_entries_movement_type_enum"`);
        await queryRunner.query(`DROP TABLE "items"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TYPE "public"."locations_type_enum"`);
        await queryRunner.query(`DROP TABLE "showrooms"`);
        await queryRunner.query(`DROP TABLE "storage_manager_assignments"`);
        await queryRunner.query(`DROP TABLE "storages"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TYPE "public"."branches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40e33edcfd30b61d159b0e0d02"`);
        await queryRunner.query(`DROP TABLE "stock_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."stock_transfers_status_enum"`);
        await queryRunner.query(`DROP TABLE "stock_transfer_lines"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP TYPE "public"."organizations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b5dfb942739d0c904d5dd04fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71834fad2b491b8e5785356bca"`);
        await queryRunner.query(`DROP TABLE "pos_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."pos_sessions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_return_doc_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c976002885a583ebfda7a9a724"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43101b2c2754f142b37a8f26b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a09d181d39d5a79e92435065e"`);
        await queryRunner.query(`DROP TABLE "pos_returns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9704f89f96a3be314504fb4acd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edba47a74e2e1b4147463774e5"`);
        await queryRunner.query(`DROP TABLE "pos_return_lines"`);
        await queryRunner.query(`DROP INDEX "public"."uq_sale_doc_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7de8ee191320f8396f0c7e1231"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1cd545f0817b4fd7e4deead10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbe9d25407df6ece81af558efa"`);
        await queryRunner.query(`DROP TABLE "pos_sales"`);
        await queryRunner.query(`DROP TYPE "public"."pos_sales_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b44d3e7e99b20e38b6025720f"`);
        await queryRunner.query(`DROP TABLE "pos_payments"`);
        await queryRunner.query(`DROP TYPE "public"."pos_payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23e4ee5117211792abb4e14793"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbd5bec7069236e5b32f629d74"`);
        await queryRunner.query(`DROP TABLE "pos_sale_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a876464727131dd5bfc36969f0"`);
        await queryRunner.query(`DROP TABLE "pos_session_reconciliations"`);
        await queryRunner.query(`DROP TABLE "registration_requests"`);
        await queryRunner.query(`DROP TYPE "public"."registration_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registration_requests_type_enum"`);
        await queryRunner.query(`DROP TABLE "sales_manager_assignments"`);
        await queryRunner.query(`DROP TABLE "salesman_assignments"`);
    }

}
