import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * FCM device registry for the mobile apps (notification module, phase P1).
 *
 * Keyed by `(installation_id, app)` — an id the app generates once per install —
 * NOT by the FCM token: tokens rotate, and keying on them would leave a stale row
 * behind on every rotation. A partial unique index on `fcm_token` guarantees one
 * live token never belongs to two users (shared store tablets hand over between
 * shifts; the previous user must stop receiving that store's pushes).
 */
export class CreateUserDevices1790060000000 implements MigrationInterface {
  name = 'CreateUserDevices1790060000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "user_devices" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "organization_id" uuid NOT NULL,
        "user_id" uuid NOT NULL,
        "installation_id" character varying(64) NOT NULL,
        "app" character varying(32) NOT NULL,
        "platform" character varying(16) NOT NULL,
        "fcm_token" text NOT NULL,
        "locale" character varying(8) NOT NULL DEFAULT 'vi',
        "app_version" character varying(32),
        "environment" character varying(16),
        "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "revoked_at" TIMESTAMP WITH TIME ZONE,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_user_devices" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_user_devices_installation_app" UNIQUE ("installation_id", "app"),
        CONSTRAINT "FK_user_devices_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
      )`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_user_devices_token_active" ON "user_devices" ("fcm_token") WHERE "revoked_at" IS NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_user_devices_user_active" ON "user_devices" ("user_id") WHERE "revoked_at" IS NULL`,
    );
    await queryRunner.query(`COMMENT ON TABLE "user_devices" IS 'Mobile app installations registered for push notifications (FCM)'`);
    await queryRunner.query(`COMMENT ON COLUMN "user_devices"."installation_id" IS 'UUID generated by the app once per install; stable across FCM token rotation'`);
    await queryRunner.query(`COMMENT ON COLUMN "user_devices"."app" IS 'Which mobile app: erp_manager | erp_sales'`);
    await queryRunner.query(`COMMENT ON COLUMN "user_devices"."locale" IS 'App language at registration; push text is rendered in this locale'`);
    await queryRunner.query(`COMMENT ON COLUMN "user_devices"."environment" IS 'App build environment (diagnostic only)'`);
    await queryRunner.query(`COMMENT ON COLUMN "user_devices"."revoked_at" IS 'Set on logout or when FCM reports the token dead; revoked rows never receive pushes'`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "user_devices"`);
  }
}
