export enum DomainEventType {
  SALE_POSTED = 'SALE_POSTED',
  INVOICE_CANCELLED = 'INVOICE_CANCELLED',
  STOCK_MOVEMENT_POSTED = 'STOCK_MOVEMENT_POSTED',
  STOCK_DEDUCTION_REQUESTED = 'STOCK_DEDUCTION_REQUESTED',
  JOURNAL_POSTED = 'JOURNAL_POSTED',
  JOURNAL_REVERSED = 'JOURNAL_REVERSED',
  JOURNAL_POST_SALE_REQUESTED = 'JOURNAL_POST_SALE_REQUESTED',
  LOYALTY_POINTS_AWARD_REQUESTED = 'LOYALTY_POINTS_AWARD_REQUESTED',
  CASH_MOVEMENT_FROM_PAYMENT_REQUESTED = 'CASH_MOVEMENT_FROM_PAYMENT_REQUESTED',
  CUSTOMER_MERGED = 'CUSTOMER_MERGED',
  SALESMAN_ASSIGNED = 'SALESMAN_ASSIGNED',
  SALESMAN_UNASSIGNED = 'SALESMAN_UNASSIGNED',
  SALES_MANAGER_ASSIGNED = 'SALES_MANAGER_ASSIGNED',
  SALES_MANAGER_UNASSIGNED = 'SALES_MANAGER_UNASSIGNED',
}

export enum DeadLetterStatus {
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}

export interface DomainEvent<T = unknown> {
  eventId: string;
  eventType: DomainEventType;
  timestamp: string;
  organizationId: string;
  branchId?: string;
  correlationId: string;
  payload: T;
}
