import { createDefaultEmployeeAccess } from "./employee-access";
import {
  AccessModeEnum,
  EmployeeRoleCategoryEnum,
  EmploymentStatusEnum,
  GenderEnum,
  MaritalStatusEnum,
  WeekdayEnum,
  type Employee,
  type MockJobPosition,
  type MockRole,
} from "./employee.types";

export const MOCK_ROLES: MockRole[] = [
  {
    id: "role-admin",
    name: "Quản trị hệ thống",
    description: "Thực hiện tất cả các chức năng trên toàn hệ thống",
    quickPick: true,
  },
  {
    id: "role-chain",
    name: "Quản lý chuỗi",
    description: "Quản lý nhiều chi nhánh trong chuỗi cửa hàng",
    quickPick: true,
  },
  {
    id: "role-sales-staff",
    name: "Nhân viên bán hàng",
    description: "Tư vấn bán hàng",
    category: EmployeeRoleCategoryEnum.SALES,
  },
  {
    id: "role-sales-online",
    name: "Nhân viên bán hàng Online",
    description:
      "Tư vấn bán hàng và ghi nhận đơn hàng trên các kênh bán hàng online",
    category: EmployeeRoleCategoryEnum.SALES,
  },
  {
    id: "role-price-adjust",
    name: "Điều chỉnh giá bán",
    description: "Thay đổi giá bán của hàng hóa khi bán hàng",
    category: EmployeeRoleCategoryEnum.SALES,
  },
  {
    id: "role-cashier",
    name: "Thu ngân",
    description: "Tư vấn bán hàng, thu tiền và quản lý quỹ tiền",
    category: EmployeeRoleCategoryEnum.SALES,
  },
  {
    id: "role-cashier-transfer",
    name: "Thu ngân kiêm điều chuyển",
    description:
      "Tư vấn bán hàng, thu tiền, quản lý quỹ tiền và lập, duyệt yêu cầu điều chuyển hàng hóa",
    category: EmployeeRoleCategoryEnum.SALES,
  },
  {
    id: "role-invoice-edit",
    name: "Sửa, hủy hóa đơn",
    description:
      "Cho phép thu ngân sửa, hủy hóa đơn trên ứng dụng bán hàng trên web",
    category: EmployeeRoleCategoryEnum.SALES,
  },
  {
    id: "role-marketing",
    name: "Nhân viên marketing",
    description:
      "Giới thiệu hàng hóa và đăng các chương trình khuyến mại trên các kênh bán hàng online",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-purchasing",
    name: "Mua hàng",
    description: "Lập đơn đặt hàng, nhập hàng",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-online-sales-mgmt",
    name: "Quản lý bán hàng online",
    description:
      "Quản lý tất cả các hoạt động của cửa hàng trên các kênh bán hàng online",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-barcode",
    name: "Quản lý tem mã",
    description: "Thực hiện in tem mã vạch hàng hóa",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-cash-fund",
    name: "Quản lý quỹ tiền mặt",
    description: "Thu - chi tiền mặt và quản lý quỹ tiền mặt",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-accountant",
    name: "Kế toán",
    description:
      "Lập đơn đặt hàng, nhập hàng, nhập - xuất hàng hóa, quản lý kho và ghi nhận các khoản thu, chi",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-store-manager",
    name: "Quản lý cửa hàng",
    description: "Quản lý tất cả các hoạt động của cửa hàng",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-product-mgmt",
    name: "Quản lý hàng hóa",
    description: "Tạo lập, chỉnh sửa danh mục hàng hóa và in tem nhãn",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-warehouse",
    name: "Quản lý kho",
    description: "Nhập - xuất hàng hóa, quản lý tồn kho",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-expense-mgmt",
    name: "Quản lý chi phí",
    description: "Tổng hợp các khoản chi phí phát sinh hàng tháng",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
  {
    id: "role-promotion-mgmt",
    name: "Quản lý khuyến mại",
    description: "Thiết lập và quản lý các chương trình khuyến mại",
    category: EmployeeRoleCategoryEnum.MANAGEMENT,
  },
];

export const MOCK_JOB_POSITIONS: MockJobPosition[] = [
  { id: "pos-cashier", name: "Thu ngân" },
  { id: "pos-manager", name: "Quản lý cửa hàng" },
  { id: "pos-sales", name: "Nhân viên kinh doanh" },
  { id: "pos-warehouse", name: "Thủ kho" },
];

const emptyAddress = () => ({
  address: "",
  country: "Việt Nam",
  province: "",
  district: "",
  ward: "",
});

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    code: "NV000001",
    fullName: "Phan Thanh Hà",
    gender: GenderEnum.FEMALE,
    birthDate: "1990-05-12",
    phone: "0901234567",
    email: "ha.phan@example.com",
    employmentStatus: EmploymentStatusEnum.OFFICIAL,
    allowSoftwareAccess: true,
    roles: [MOCK_ROLES[0]!, MOCK_ROLES[1]!],
    contact: {
      mobile: "0901234567",
      homePhone: "02923765432",
      email: "ha.phan@example.com",
      address: "123 Nguyễn Văn Cừ, Ninh Kiều, Cần Thơ",
    },
    emergencyContact: {
      fullName: "Phan Văn A",
      relationship: "Cha",
      mobile: "0912345678",
      homePhone: "",
      email: "",
      address: "123 Nguyễn Văn Cừ, Ninh Kiều, Cần Thơ",
    },
    profile: {
      jobPositionId: "pos-manager",
      probationDate: "2018-01-01",
      officialDate: "2018-04-01",
      salary: 15000000,
      deposit: 0,
      originalDocumentsNote: "Hồ sơ gốc đầy đủ",
    },
    access: createDefaultEmployeeAccess(),
    basicExtra: {
      idCardNumber: "079090012345",
      idCardIssuePlace: "Cục Cảnh sát QLHC về TTXH",
      idCardIssueDate: "2015-06-01",
      maritalStatus: MaritalStatusEnum.SINGLE,
    },
    contactDetail: {
      homePhone: "02923765432",
      permanentAddress: {
        address: "123 Nguyễn Văn Cừ",
        country: "Việt Nam",
        province: "Cần Thơ",
        district: "Ninh Kiều",
        ward: "An Hòa",
      },
      currentAddress: {
        address: "123 Nguyễn Văn Cừ",
        country: "Việt Nam",
        province: "Cần Thơ",
        district: "Ninh Kiều",
        ward: "An Hòa",
      },
    },
  },
  {
    id: "emp-2",
    code: "NV000002",
    fullName: "Nguyễn Văn Thiên",
    gender: GenderEnum.MALE,
    birthDate: "1995-08-20",
    phone: "0987654321",
    email: "thien.nguyen@example.com",
    employmentStatus: EmploymentStatusEnum.OFFICIAL,
    allowSoftwareAccess: true,
    roles: [MOCK_ROLES[2]!],
    contact: {
      mobile: "0987654321",
      homePhone: "",
      email: "thien.nguyen@example.com",
      address: "45 Trần Hưng Đạo, Quận 1, TP.HCM",
    },
    emergencyContact: {
      fullName: "Nguyễn Thị B",
      relationship: "Mẹ",
      mobile: "0977123456",
      homePhone: "",
      email: "b.nguyen@example.com",
      address: "45 Trần Hưng Đạo, Quận 1, TP.HCM",
    },
    profile: {
      jobPositionId: "pos-cashier",
      officialDate: "2020-03-15",
      salary: 8000000,
      deposit: 500000,
      originalDocumentsNote: "",
    },
    access: createDefaultEmployeeAccess(),
    contactDetail: {
      homePhone: "",
      permanentAddress: {
        address: "45 Trần Hưng Đạo",
        country: "Việt Nam",
        province: "TP.HCM",
        district: "Quận 1",
        ward: "Bến Nghé",
      },
      currentAddress: emptyAddress(),
    },
  },
  {
    id: "emp-3",
    code: "NV000003",
    fullName: "Trần Thị Mai",
    gender: GenderEnum.FEMALE,
    birthDate: "1998-11-03",
    phone: "0933445566",
    employmentStatus: EmploymentStatusEnum.PROBATION,
    allowSoftwareAccess: true,
    roles: [MOCK_ROLES[3]!],
    contact: {
      mobile: "0933445566",
      homePhone: "0241234567",
      email: "",
      address: "12 Lê Lợi, Hoàn Kiếm, Hà Nội",
    },
    emergencyContact: {
      fullName: "Trần Văn C",
      relationship: "Anh trai",
      mobile: "0909887766",
      homePhone: "",
      email: "",
      address: "",
    },
    profile: {
      jobPositionId: "pos-warehouse",
      probationDate: "2025-01-10",
      salary: 7000000,
      deposit: 0,
      originalDocumentsNote: "",
    },
    access: createDefaultEmployeeAccess(),
    contactDetail: {
      homePhone: "0241234567",
      permanentAddress: {
        address: "12 Lê Lợi",
        country: "Việt Nam",
        province: "Hà Nội",
        district: "Hoàn Kiếm",
        ward: "Hàng Bài",
      },
      currentAddress: emptyAddress(),
    },
  },
  {
    id: "emp-4",
    code: "NV000004",
    fullName: "Lê Hoàng Nam",
    gender: GenderEnum.MALE,
    birthDate: "1988-02-28",
    phone: "0911223344",
    email: "nam.le@example.com",
    employmentStatus: EmploymentStatusEnum.RESIGNED,
    allowSoftwareAccess: false,
    roles: [],
    contact: {
      mobile: "0911223344",
      homePhone: "",
      email: "nam.le@example.com",
      address: "",
    },
    emergencyContact: {
      fullName: "",
      relationship: "",
      mobile: "",
      homePhone: "",
      email: "",
      address: "",
    },
    profile: {
      salary: 0,
      deposit: 0,
      originalDocumentsNote: "",
    },
    access: {
      mode: AccessModeEnum.SCHEDULED,
      schedule: createDefaultEmployeeAccess().schedule.map((day) =>
        day.weekday === WeekdayEnum.SATURDAY || day.weekday === WeekdayEnum.SUNDAY
          ? { ...day, enabled: false }
          : day,
      ),
    },
    contactDetail: {
      homePhone: "",
      permanentAddress: emptyAddress(),
      currentAddress: emptyAddress(),
    },
  },
  {
    id: "emp-5",
    code: "CT1",
    fullName: "Võ Minh Tuấn",
    gender: GenderEnum.MALE,
    birthDate: "1992-07-15",
    phone: "0944556677",
    employmentStatus: EmploymentStatusEnum.OFFICIAL,
    allowSoftwareAccess: true,
    roles: [MOCK_ROLES[2]!, MOCK_ROLES[3]!],
    contact: {
      mobile: "0944556677",
      homePhone: "02923888888",
      email: "tuan.vo@example.com",
      address: "88 Mậu Thân, Ninh Kiều, Cần Thơ",
    },
    emergencyContact: {
      fullName: "Võ Thị D",
      relationship: "Vợ",
      mobile: "0944667788",
      homePhone: "",
      email: "",
      address: "88 Mậu Thân, Ninh Kiều, Cần Thơ",
    },
    profile: {
      jobPositionId: "pos-sales",
      officialDate: "2019-09-01",
      salary: 10000000,
      deposit: 1000000,
      originalDocumentsNote: "Bằng đại học, CMND",
    },
    access: createDefaultEmployeeAccess(),
    contactDetail: {
      homePhone: "02923888888",
      permanentAddress: {
        address: "88 Mậu Thân",
        country: "Việt Nam",
        province: "Cần Thơ",
        district: "Ninh Kiều",
        ward: "An Khánh",
      },
      currentAddress: {
        address: "88 Mậu Thân",
        country: "Việt Nam",
        province: "Cần Thơ",
        district: "Ninh Kiều",
        ward: "An Khánh",
      },
    },
  },
];
