import { REPORT_FILTERS_LINE } from "../report-filters.constant";
import { ReportTableColumn, ReportTableColumnGroup, ReportTableColumnLabel } from "../report-table.constant";
import { ReportTableConfig } from "../report.interface";

export const single_tableRegistryReportDailySaleSummary: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns: [
    {
      column: ReportTableColumn.DATE,
      backendField: "date",
      label: ReportTableColumnLabel[ReportTableColumn.DATE],
      order: 1,
      visible: true,
      number: 0,
      tableConfig: { width: 96, pinned: "left", align: "left", dataType: "date", link: true },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_TOTAL,
      backendField: "revenueTotal",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_TOTAL],
      order: 2,
      visible: true,
      number: 1,
      formulaDisplay: "(3)+(4)-(5)-(14)",
      tableConfig: { width: 124 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_GOODS,
      backendField: "revenueGoods",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_GOODS],
      order: 3,
      visible: true,
      number: 3,
      tableConfig: { width: 112 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_FEE,
      backendField: "revenueFee",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_FEE],
      order: 4,
      visible: true,
      number: 4,
      tableConfig: { width: 90 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_PROMOTION,
      backendField: "revenuePromotion",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_PROMOTION],
      order: 5,
      visible: true,
      number: 5,
      tableConfig: { width: 96 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_DISCOUNT_POINT,
      backendField: "revenueDiscountPoint",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_POINT],
      order: 6,
      visible: true,
      number: 14,
      tableConfig: { width: 90 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_DISCOUNT_RATE,
      backendField: "revenueDiscountRate",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_RATE],
      order: 7,
      visible: true,
      number: 6,
      tableConfig: { width: 96 },
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_CASH,
      backendField: "paymentCash",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_CASH],
      order: 8,
      visible: true,
      number: 7,
      tableConfig: { width: 104 },
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_AMEX_DEBIT,
      backendField: "paymentAmexDebit",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX_DEBIT],
      order: 9,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_AMEX,
      backendField: "paymentAmex",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX],
      order: 10,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_ATM,
      backendField: "paymentAtm",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_ATM],
      order: 11,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_TRANSFER,
      backendField: "paymentTransfer",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_TRANSFER],
      order: 12,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_DINERS,
      backendField: "paymentDiners",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DINERS],
      order: 13,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_DISCOVER,
      backendField: "paymentDiscover",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DISCOVER],
      order: 14,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_JCB,
      backendField: "paymentJcb",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_JCB],
      order: 15,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_MASTERCARD_DEBIT,
      backendField: "paymentMastercardDebit",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD_DEBIT],
      order: 16,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_MASTERCARD,
      backendField: "paymentMastercard",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD],
      order: 17,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_QR_TECHCOMBANK,
      backendField: "paymentQrTechcombank",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_QR_TECHCOMBANK],
      order: 18,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_UNIONPAY,
      backendField: "paymentUnionpay",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_UNIONPAY],
      order: 19,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_VISA_DEBIT,
      backendField: "paymentVisaDebit",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA_DEBIT],
      order: 20,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_VISA,
      backendField: "paymentVisa",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA],
      order: 21,
      visible: true,
    },
    {
      column: ReportTableColumn.NET_REVENUE,
      backendField: "netRevenue",
      label: ReportTableColumnLabel[ReportTableColumn.NET_REVENUE],
      order: 22,
      visible: true,
      number: 13,
      formulaDisplay: "(1)-(11)-(12)",
      tableConfig: { width: 360, pinned: "right" },
    },
  ],
};

export const chain_tableRegistryReportDailySaleSummary: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns: [
    {
      column: ReportTableColumn.DATE,
      backendField: "date",
      label: ReportTableColumnLabel[ReportTableColumn.DATE],
      order: 1,
      visible: true,
      number: 0,
      tableConfig: { width: 96, pinned: "left", align: "left", dataType: "date", link: true },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_TOTAL,
      backendField: "revenueTotal",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_TOTAL],
      order: 2,
      visible: true,
      number: 1,
      formulaDisplay: "(3)+(4)-(5)-(14)",
      tableConfig: { width: 124 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_GOODS,
      backendField: "revenueGoods",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_GOODS],
      order: 3,
      visible: true,
      number: 3,
      tableConfig: { width: 112 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_FEE,
      backendField: "revenueFee",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_FEE],
      order: 4,
      visible: true,
      number: 4,
      tableConfig: { width: 90 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_PROMOTION,
      backendField: "revenuePromotion",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_PROMOTION],
      order: 5,
      visible: true,
      number: 5,
      tableConfig: { width: 96 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_DISCOUNT_POINT,
      backendField: "revenueDiscountPoint",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_POINT],
      order: 6,
      visible: true,
      number: 14,
      tableConfig: { width: 90 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_DISCOUNT_RATE,
      backendField: "revenueDiscountRate",
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_RATE],
      order: 7,
      visible: true,
      number: 6,
      tableConfig: { width: 96 },
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_CASH,
      backendField: "paymentCash",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_CASH],
      order: 8,
      visible: true,
      number: 7,
      tableConfig: { width: 104 },
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_AMEX_DEBIT,
      backendField: "paymentAmexDebit",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX_DEBIT],
      order: 9,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_AMEX,
      backendField: "paymentAmex",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX],
      order: 10,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_ATM,
      backendField: "paymentAtm",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_ATM],
      order: 11,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_TRANSFER,
      backendField: "paymentTransfer",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_TRANSFER],
      order: 12,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_DINERS,
      backendField: "paymentDiners",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DINERS],
      order: 13,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_DISCOVER,
      backendField: "paymentDiscover",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DISCOVER],
      order: 14,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_JCB,
      backendField: "paymentJcb",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_JCB],
      order: 15,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_MASTERCARD_DEBIT,
      backendField: "paymentMastercardDebit",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD_DEBIT],
      order: 16,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_MASTERCARD,
      backendField: "paymentMastercard",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD],
      order: 17,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_QR_TECHCOMBANK,
      backendField: "paymentQrTechcombank",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_QR_TECHCOMBANK],
      order: 18,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_UNIONPAY,
      backendField: "paymentUnionpay",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_UNIONPAY],
      order: 19,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_VISA_DEBIT,
      backendField: "paymentVisaDebit",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA_DEBIT],
      order: 20,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_VISA,
      backendField: "paymentVisa",
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA],
      order: 21,
      visible: true,
    },
    {
      column: ReportTableColumn.NET_REVENUE,
      backendField: "netRevenue",
      label: ReportTableColumnLabel[ReportTableColumn.NET_REVENUE],
      order: 22,
      visible: true,
      number: 13,
      formulaDisplay: "(1)-(11)-(12)",
      tableConfig: { width: 360, pinned: "right" },
    },
  ],
};

export const single_filterRegistryReportDailySaleSummary = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.CHECKBOX_STATISTIC_BY_BRAND
];

export const chain_filterRegistryReportDailySaleSummary = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.CHECKBOX_STATISTIC_BY_BRAND
];