import { REPORT_FILTERS_LINE } from "../report-filters.constant";
import { ReportTableColumn } from "../report-table.constant";
import { ReportColumnConfig, ReportTableConfig } from "../report.interface";

const columns: ReportColumnConfig[] = [
  {
    column: ReportTableColumn.DATE,
    backendField: "date",
    label: "Ngày",
    order: 1,
    visible: true,
    tableConfig: { width: 96, pinned: "left", align: "left", dataType: "date" },
  },
  {
    column: ReportTableColumn.HOUR,
    backendField: "hour",
    label: "Giờ",
    order: 2,
    visible: true,
    tableConfig: { width: 72, align: "left", dataType: "text", filterKind: "time" },
  },
  {
    column: ReportTableColumn.INVOICE_CODE,
    backendField: "invoiceCode",
    label: "Số hóa đơn",
    order: 3,
    visible: true,
    tableConfig: { width: 124, align: "left", dataType: "text", link: true },
  },
  {
    column: ReportTableColumn.SKU,
    backendField: "sku",
    label: "Mã SKU",
    order: 4,
    visible: true,
    tableConfig: { width: 110, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.PRODUCT_NAME,
    backendField: "productName",
    label: "Tên hàng hóa",
    order: 5,
    visible: true,
    tableConfig: { width: 200, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.PRODUCT_GROUP,
    backendField: "productGroup",
    label: "Nhóm hàng hóa",
    order: 6,
    visible: true,
    tableConfig: { width: 140, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.UNIT,
    backendField: "unit",
    label: "Đơn vị tính",
    order: 7,
    visible: true,
    tableConfig: { width: 80, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.QUANTITY,
    backendField: "quantity",
    label: "Số lượng",
    order: 8,
    visible: true,
    tableConfig: { width: 90 },
  },
  {
    column: ReportTableColumn.UNIT_PRICE,
    backendField: "unitPrice",
    label: "Đơn giá",
    order: 9,
    visible: true,
    tableConfig: { width: 110 },
  },
  {
    column: ReportTableColumn.REVENUE_GOODS,
    backendField: "revenueGoods",
    label: "Tiền hàng",
    order: 10,
    visible: true,
    tableConfig: { width: 120 },
  },
  {
    column: ReportTableColumn.REVENUE_PROMOTION,
    backendField: "revenuePromotion",
    label: "Tiền KM",
    order: 11,
    visible: true,
    tableConfig: { width: 110 },
  },
  {
    column: ReportTableColumn.REVENUE_TOTAL,
    backendField: "revenueTotal",
    label: "Doanh thu",
    order: 12,
    visible: true,
    tableConfig: { width: 120 },
  },
  {
    column: ReportTableColumn.REFERENCE_CODE,
    backendField: "referenceCode",
    label: "Tham chiếu",
    order: 13,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.PAYMENT_BANK_ACCOUNT,
    backendField: "paymentBankAccount",
    label: "Tài khoản ngân hàng",
    order: 14,
    visible: true,
    tableConfig: { width: 150, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CUSTOMER_CODE,
    backendField: "customerCode",
    label: "Mã khách hàng",
    order: 15,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CUSTOMER_NAME,
    backendField: "customerName",
    label: "Khách hàng",
    order: 16,
    visible: true,
    tableConfig: { width: 150, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CUSTOMER_GROUP,
    backendField: "customerGroup",
    label: "Nhóm khách hàng",
    order: 17,
    visible: true,
    tableConfig: { width: 140, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CUSTOMER_PHONE,
    backendField: "customerPhone",
    label: "Số điện thoại",
    order: 18,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CHANNEL,
    backendField: "channel",
    label: "Kênh bán hàng",
    order: 19,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CASHIER_NAME,
    backendField: "cashierName",
    label: "Thu ngân",
    order: 20,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.EMPLOYEE_NAME,
    backendField: "employeeName",
    label: "NV bán hàng",
    order: 21,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.NOTE_ORDER,
    backendField: "noteOrder",
    label: "Ghi chú hóa đơn",
    order: 22,
    visible: true,
    tableConfig: { width: 160, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.NOTE_PRODUCT,
    backendField: "noteProduct",
    label: "Ghi chú hàng hóa",
    order: 23,
    visible: true,
    tableConfig: { width: 160, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.SUPPLIER_NAME,
    backendField: "supplierName",
    label: "Nhà cung cấp",
    order: 24,
    visible: true,
    tableConfig: { width: 150, align: "left", dataType: "text" },
  },
];

export const single_tableRegistryReportRevenueDetailByInvoiceAndProduct: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns,
};

export const chain_tableRegistryReportRevenueDetailByInvoiceAndProduct: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns,
};

export const single_filterRegistryReportRevenueDetailByInvoiceAndProduct = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.INVOICE_STATUS,
  REPORT_FILTERS_LINE.STAT_DATE_TYPE,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.PRODUCT_GROUP,
  REPORT_FILTERS_LINE.CASHIER,
  REPORT_FILTERS_LINE.SALESPERSON,
  REPORT_FILTERS_LINE.CUSTOMER,
];

export const chain_filterRegistryReportRevenueDetailByInvoiceAndProduct = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.INVOICE_STATUS,
  REPORT_FILTERS_LINE.STAT_DATE_TYPE,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.PRODUCT_GROUP,
  REPORT_FILTERS_LINE.CASHIER,
  REPORT_FILTERS_LINE.SALESPERSON,
  REPORT_FILTERS_LINE.CUSTOMER,
];
