import { REPORT_FILTERS_LINE } from "../report-filters.constant";

export const single_filterRegistryReportRevenueByProduct = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.PRODUCT_TYPE,
  REPORT_FILTERS_LINE.STATISTIC_BY,
  REPORT_FILTERS_LINE.PRODUCT_GROUP,
  REPORT_FILTERS_LINE.BRAND,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.CHECKBOX_STATISTIC_BY_BRAND,
  REPORT_FILTERS_LINE.CHECKBOX_ALLOCATE_COMBO,
];

export const chain_filterRegistryReportRevenueByProduct = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.PRODUCT_TYPE,
  REPORT_FILTERS_LINE.STATISTIC_BY,
  REPORT_FILTERS_LINE.PRODUCT_GROUP,
  REPORT_FILTERS_LINE.BRAND,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.CHECKBOX_STATISTIC_BY_BRAND,
  REPORT_FILTERS_LINE.CHECKBOX_ALLOCATE_COMBO,
];
