import { REPORT_FILTERS_LINE } from "../report-filters.constant";
import {
  ReportTableColumn,
  ReportTableColumnGroup,
} from "../report-table.constant";
import { ReportColumnConfig, ReportTableConfig } from "../report.interface";

const columns: ReportColumnConfig[] = [
  {
    column: ReportTableColumn.DATE,
    backendField: "date",
    label: "Ngày",
    order: 1,
    visible: true,
    tableConfig: { width: 96, pinned: "left", align: "left", dataType: "date", link: true },
  },
  {
    column: ReportTableColumn.HOUR,
    backendField: "hour",
    label: "Giờ",
    order: 2,
    visible: true,
    tableConfig: { width: 72, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.INVOICE_CODE,
    backendField: "invoiceCode",
    label: "Số hóa đơn",
    order: 3,
    visible: true,
    tableConfig: { width: 124, align: "left", dataType: "text", link: true },
  },
  {
    column: ReportTableColumn.STATUS,
    backendField: "status",
    label: "Trạng thái",
    order: 4,
    visible: true,
    tableConfig: { width: 110, align: "left", dataType: "text" },
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_TOTAL,
    backendField: "revenueTotal",
    label: "Tổng",
    order: 5,
    visible: true,
    number: 1,
    formulaDisplay: "(3)+(4)-(5)-(16)",
    tableConfig: { width: 120 },
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_GOODS,
    backendField: "revenueGoods",
    label: "Tiền hàng",
    order: 6,
    visible: true,
    number: 3,
    tableConfig: { width: 110 },
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_FEE,
    backendField: "revenueFee",
    label: "Tiền phí",
    order: 7,
    visible: true,
    number: 4,
    tableConfig: { width: 100 },
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_PROMOTION,
    backendField: "revenuePromotion",
    label: "Khuyến mại",
    order: 8,
    visible: true,
    number: 5,
    tableConfig: { width: 110 },
  },
  {
    group: ReportTableColumnGroup.REVENUE,
    column: ReportTableColumn.REVENUE_DISCOUNT_RATE,
    backendField: "revenueDiscountRate",
    label: "Tỷ lệ KM (%)",
    order: 9,
    visible: true,
    number: 6,
    tableConfig: { width: 100 },
  },
  {
    group: ReportTableColumnGroup.REVENUE_TMDT,
    column: ReportTableColumn.PLATFORM_FEE,
    backendField: "platformFee",
    label: "Phí trả sàn",
    order: 10,
    visible: true,
    number: 7,
    tableConfig: { width: 100 },
  },
  {
    group: ReportTableColumnGroup.REVENUE_TMDT,
    column: ReportTableColumn.PLATFORM_OTHER_INCOME,
    backendField: "platformOtherIncome",
    label: "Thu khác từ sàn",
    order: 11,
    visible: true,
    number: 17,
    tableConfig: { width: 110 },
  },
  {
    group: ReportTableColumnGroup.REVENUE_TMDT,
    column: ReportTableColumn.PLATFORM_REVENUE,
    backendField: "platformRevenue",
    label: "Doanh thu từ sàn",
    order: 12,
    visible: true,
    number: 8,
    tableConfig: { width: 120 },
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_CASH,
    backendField: "paymentCash",
    label: "Tiền mặt",
    order: 13,
    visible: true,
    number: 9,
    tableConfig: { width: 100 },
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_BANK_DEPOSIT,
    backendField: "paymentBankDeposit",
    label: "Tiền gửi NH",
    order: 14,
    visible: true,
    number: 10,
    tableConfig: { width: 110 },
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_VOUCHER,
    backendField: "paymentVoucher",
    label: "Voucher",
    order: 15,
    visible: true,
    number: 11,
    tableConfig: { width: 90 },
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_POINT,
    backendField: "paymentPoint",
    label: "Điểm",
    order: 16,
    visible: true,
    number: 12,
    tableConfig: { width: 90 },
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_DEBT,
    backendField: "paymentDebt",
    label: "Công nợ",
    order: 17,
    visible: true,
    number: 13,
    tableConfig: { width: 100 },
  },
  {
    group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
    column: ReportTableColumn.PAYMENT_COLLECT,
    backendField: "paymentCollect",
    label: "Thu hộ",
    order: 18,
    visible: true,
    number: 14,
    tableConfig: { width: 90 },
  },
  {
    column: ReportTableColumn.PAYMENT_BANK_ACCOUNT,
    backendField: "paymentBankAccount",
    label: "Tài khoản ngân hàng",
    order: 19,
    visible: true,
    tableConfig: { width: 150, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CUSTOMER_NAME,
    backendField: "customerName",
    label: "Khách hàng",
    order: 20,
    visible: true,
    tableConfig: { width: 150, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CUSTOMER_PHONE,
    backendField: "customerPhone",
    label: "Số điện thoại",
    order: 21,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CHANNEL,
    backendField: "channel",
    label: "Kênh bán hàng",
    order: 22,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.CASHIER_NAME,
    backendField: "cashierName",
    label: "Thu ngân",
    order: 23,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.EMPLOYEE_NAME,
    backendField: "employeeName",
    label: "NV bán hàng",
    order: 24,
    visible: true,
    tableConfig: { width: 120, align: "left", dataType: "text" },
  },
  {
    column: ReportTableColumn.NOTE,
    backendField: "note",
    label: "Ghi chú",
    order: 25,
    visible: true,
    tableConfig: { width: 140, align: "left", dataType: "text" },
  },
];

export const single_tableRegistryReportInvoiceAndOrderList: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns,
};

export const chain_tableRegistryReportInvoiceAndOrderList: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns,
};

export const single_filterRegistryReportInvoiceAndOrderList = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.INVOICE_STATUS,
  REPORT_FILTERS_LINE.STAT_DATE_TYPE,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.CASHIER,
  REPORT_FILTERS_LINE.SALESPERSON,
  REPORT_FILTERS_LINE.CUSTOMER,
]

export const chain_filterRegistryReportInvoiceAndOrderList = [
  REPORT_FILTERS_LINE.STORE,
  REPORT_FILTERS_LINE.INVOICE_STATUS,
  REPORT_FILTERS_LINE.STAT_DATE_TYPE,
  REPORT_FILTERS_LINE.REPORT_PERIOD,
  REPORT_FILTERS_LINE.RANGE_DATE,
  REPORT_FILTERS_LINE.CASHIER,
  REPORT_FILTERS_LINE.SALESPERSON,
  REPORT_FILTERS_LINE.CUSTOMER,
]