import { Entity, Column, Index, OneToMany, DeleteDateColumn } from "typeorm";
import { StockTakeStatus } from "@erp/shared-interfaces";
import { BaseEntity } from "../../../database/entities/base.entity";
import { StockTakeLineEntity } from "./stock-take-line.entity";
import { StockTakeMemberEntity } from "./stock-take-member.entity";

@Entity("stock_takes")
@Index(["organizationId", "status"])
@Index("IDX_stock_takes_org_branch_list", [
  "organizationId",
  "branchId",
  "status",
  "createdAt",
])
export class StockTakeEntity extends BaseEntity {
  @Column({ name: "document_number", nullable: true })
  documentNumber?: string;

  @Column({
    type: "enum",
    enum: StockTakeStatus,
    default: StockTakeStatus.DRAFT,
  })
  status: StockTakeStatus;

  @Column({ name: "storage_id", type: "uuid", nullable: true })
  storageId?: string;

  @Column({ name: "location_id", type: "uuid", nullable: true })
  locationId?: string;

  /** Mục đích — free-text purpose written by user on the form. */
  @Column({ type: "text", nullable: true })
  purpose?: string;

  @Column({ name: "count_by_value", type: "boolean", default: false })
  countByValue: boolean;

  /** Kiểm kê đến ngày — planned cutoff date chosen in the create dialog (date only, no time). */
  @Column({ name: "planned_date", type: "date", nullable: true })
  plannedDate?: string;

  /** Ngày + giờ kiểm kê thực tế — defaults to now() on create. */
  @Column({ name: "counted_at", type: "timestamptz", nullable: true })
  countedAt?: Date;

  /** Kết luận — conclusion text shown at the bottom of the form. */
  @Column({ type: "text", nullable: true })
  conclusion?: string;

  @Column({ name: "snapshot_at", type: "timestamptz" })
  snapshotAt: Date;

  @Column({ type: "text", nullable: true })
  notes?: string;

  @Column({ name: "posted_at", type: "timestamptz", nullable: true })
  postedAt?: Date;

  @Column({ name: "posted_by", type: "uuid", nullable: true })
  postedBy?: string;

  /** IDs of the goods-receipt/goods-issue documents auto-generated by process(). */
  @Column({ name: "generated_receipt_id", type: "uuid", nullable: true })
  generatedReceiptId?: string;

  @Column({ name: "generated_issue_id", type: "uuid", nullable: true })
  generatedIssueId?: string;

  /** Set on source vouchers after they are saved into a merged stock-take. */
  @Column({ name: "merged_into_id", type: "uuid", nullable: true })
  mergedIntoId?: string | null;

  /** Audit trail retained on the merged voucher. */
  @Column({
    name: "merge_source_ids",
    type: "uuid",
    array: true,
    nullable: true,
  })
  mergeSourceIds?: string[] | null;

  @Column({ name: "merged_at", type: "timestamptz", nullable: true })
  mergedAt?: Date | null;

  @DeleteDateColumn({ name: "deleted_at" })
  deletedAt?: Date;

  @OneToMany(() => StockTakeLineEntity, (line) => line.stockTake, {
    cascade: ["insert"],
    eager: true,
  })
  lines: StockTakeLineEntity[];

  @OneToMany(() => StockTakeMemberEntity, (member) => member.stockTake, {
    cascade: ["insert"],
    eager: true,
  })
  members: StockTakeMemberEntity[];
}
