import { ReportTableColumn, ReportTableColumnGroup, ReportTableColumnLabel } from "../report-table.constant";
import { ReportTableConfig } from "../report.interface";

export const ReportDailySaleSummaryTableRegistry: ReportTableConfig = {
  summaryLabel: "Tổng",
  columns: [
    {
      column: ReportTableColumn.DATE,
      label: ReportTableColumnLabel[ReportTableColumn.DATE],
      order: 1,
      visible: true,
      number: 0,
      tableConfig: { width: 96, pinned: "left", align: "left", dataType: "date", link: true },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_TOTAL,
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_TOTAL],
      order: 2,
      visible: true,
      number: 1,
      formulaDisplay: "(3)+(4)-(5)-(14)",
      tableConfig: { width: 124 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_GOODS,
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_GOODS],
      order: 3,
      visible: true,
      number: 3,
      tableConfig: { width: 112 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_FEE,
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_FEE],
      order: 4,
      visible: true,
      number: 4,
      tableConfig: { width: 90 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_PROMOTION,
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_PROMOTION],
      order: 5,
      visible: true,
      number: 5,
      tableConfig: { width: 96 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_DISCOUNT_POINT,
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_POINT],
      order: 6,
      visible: true,
      number: 14,
      tableConfig: { width: 90 },
    },
    {
      group: ReportTableColumnGroup.REVENUE,
      column: ReportTableColumn.REVENUE_DISCOUNT_RATE,
      label: ReportTableColumnLabel[ReportTableColumn.REVENUE_DISCOUNT_RATE],
      order: 7,
      visible: true,
      number: 6,
      tableConfig: { width: 96 },
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_CASH,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_CASH],
      order: 8,
      visible: true,
      number: 7,
      tableConfig: { width: 104 },
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_AMEX_DEBIT,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX_DEBIT],
      order: 9,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_AMEX,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_AMEX],
      order: 10,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_ATM,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_ATM],
      order: 11,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_TRANSFER,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_TRANSFER],
      order: 12,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_DINERS,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DINERS],
      order: 13,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_DISCOVER,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_DISCOVER],
      order: 14,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_JCB,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_JCB],
      order: 15,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_MASTERCARD_DEBIT,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD_DEBIT],
      order: 16,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_MASTERCARD,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_MASTERCARD],
      order: 17,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_QR_TECHCOMBANK,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_QR_TECHCOMBANK],
      order: 18,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_UNIONPAY,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_UNIONPAY],
      order: 19,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_VISA_DEBIT,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA_DEBIT],
      order: 20,
      visible: true,
    },
    {
      group: ReportTableColumnGroup.CUSTOMER_PAYMENT,
      column: ReportTableColumn.PAYMENT_VISA,
      label: ReportTableColumnLabel[ReportTableColumn.PAYMENT_VISA],
      order: 21,
      visible: true,
    },
    {
      column: ReportTableColumn.NET_REVENUE,
      label: ReportTableColumnLabel[ReportTableColumn.NET_REVENUE],
      order: 22,
      visible: true,
      number: 13,
      formulaDisplay: "(1)-(11)-(12)",
      tableConfig: { width: 360, pinned: "right" },
    },
  ],
};
