// ─── Internal header constants ────────────────────────────────────────────────

/** Standard 32-col import template header (TH1–TH5 input sections). */
const IH = [
  'Mã SKU', 'Mã vạch', 'Mã SKU mẫu mã', 'Tên mẫu mã', 'Tên hàng hóa (*)',
  'Mã nhóm hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size',
  'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu',
  'SL tồn tối đa', 'Kho tồn', 'Đơn vị chuyển đổi', 'Tỷ lệ',
  'Giá mua theo ĐVT chuyển đổi', 'Giá bán theo đơn vị chuyển đổi',
  'Đơn vị bán mặc định', 'Đơn vị nhập mặc định',
  'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng',
  'Vị trí trưng bày', 'Vị trí lưu kho',
  'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh',
];

/** Standard 30-col result header (starts Mã SKU;Mã vạch;Tên hàng hóa). */
const RH = [
  'Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Mã nhóm hàng hóa', 'Tên nhóm hàng hóa',
  'ĐVT', 'Màu', 'Size', 'Giá mua', 'Giá bán',
  'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu', 'SL tồn tối đa', 'Kho tồn',
  'Đơn vị chuyển đổi', 'Tỷ lệ',
  'Giá mua theo đơn vị chuyển đổi', 'Giá bán theo đơn vị chuyển đổi',
  'Đơn vị bán mặc định', 'Đơn vị nhập mặc định',
  'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng',
  'Vị trí trưng bày', 'Vị trí lưu kho',
  'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh',
];

/** TH6 37-col import header (adds lot/serial/price-list cols). */
const IH6 = [
  ...IH.slice(0, 29),
  'Quản lý theo lô, HSD', 'Bán trước ngày', 'Quản lý theo Serial/IMEI',
  'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh',
  'Giá bán buôn 1', 'Giá bán buôn 2',
];

/** TH6 35-col result header. */
const RH6 = [
  ...RH.slice(0, 27),
  'Quản lý theo lô, HSD', 'Bán trước ngày', 'Quản lý theo Serial/IMEI',
  'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh',
  'Giá bán buôn 1', 'Giá bán buôn 2',
];

// ─── Field description sheet ──────────────────────────────────────────────────

export const STATIC_FIELD_GRID: string[][] = [
  ['STT', 'Nhóm', 'Tên cột', 'Diễn giải', 'Giá trị nếu để trống'],
  ['1', 'Thông tin hàng hóa', 'Mã SKU', 'Là mã của hàng hóa (Mã lưu kho)\nMã dài tối đa 50 ký tự', 'Tự sinh theo quy tắc dựa vào tên hàng hóa'],
  ['2', '', 'Mã vạch', 'Mã dùng để in tem, quét mã vạch\nChỉ đáp ứng mã vạch gồm ký tự số, dài tối đa 20 ký tự', 'Tự sinh mã vạch theo quy tắc sinh mã'],
  ['3', '', 'Mã SKU mẫu mã', 'Mã của Mẫu mã (Hàng hóa cha). VD: Áo sơ mi có 2 size S và M thì Áo sơ mi là Mẫu mã; Áo sơ mi size S, Áo sơ mi size M là Hàng hóa\nCác hàng hóa nhập cùng 1 mã SKU mẫu mã: Là hàng hóa con của mã đã nhập\nNhập tối đa 50 ký tự', 'Hàng hóa không phải là hàng hóa con của Mẫu mã'],
  ['4', '', 'Tên mẫu mã', 'Tên của Mẫu mã (Hàng hóa cha)\nNhập tối đa 255 ký tự', 'Lấy mã SKU mẫu mã'],
  ['5', '', 'Tên hàng hóa', 'Tên của hàng hóa\nNhập tối đa 255 ký tự', 'Bắt buộc nhập, để trống thì không nhập khẩu được hàng hóa'],
  ['6', '', 'Mã nhóm hàng hóa', 'Mã nhóm hàng hóa\nTối đa 25 ký tự\nNếu phân cấp nhóm thì nhập ngăn cách bằng dấu "\\", VD: Ao\\Aosomi\nNếu nhóm hàng hóa chưa có trong danh mục thì chương trình sẽ tự thêm mới với tên và mã giống với giá trị đã nhập', 'Thêm mới nhóm hàng hóa theo tên nhóm đã nhập, nếu để trống cả tên nhóm thì sẽ coi như hàng hóa không có nhóm'],
  ['7', '', 'Tên nhóm hàng hóa', 'Nhập tối đa 128 ký tự, không chứa ký tự "\\"', 'Khi thêm mới sẽ lấy Mã nhóm làm tên nhóm'],
  ['8', '', 'ĐVT', 'Đơn vị tính cơ bản của hàng hóa.\nNên lấy đơn vị tính quản lý nhỏ nhất. VD: Vải bán theo Cuộn và Mét thì để ĐVT là Mét', 'Lấy đơn vị Chiếc'],
  ['9', '', 'Màu', 'VD: Xanh\nNếu hàng hóa không có màu thì để trống', 'Không có màu'],
  ['10', '', 'Size', 'VD: XL\nNếu hàng hóa không có size thì để trống', 'Không có size'],
  ['11', '', 'Giá mua', 'Tối đa 14 ký tự, không nhập số âm.\nGiá mua hàng hóa cần nhập là giá trước thuế.', 'Lấy = 0'],
  ['12', '', 'Giá bán', 'Tối đa 14 ký tự, không nhập số âm\nNếu cửa hàng áp dụng bán hàng với đơn giá là giá trước thuế, nhập giá trước thuế.\nNếu cửa hàng áp dụng bán hàng với đơn giá là giá sau thuế, nhập giá sau thuế.', 'Lấy = 0'],
  ['13', 'Thuế', 'Thuế suất (%)', 'Nhập nếu cửa hàng có hàng hóa với nhiều mức thuế suất khác nhau\nNhập trong các giá trị: KCT, 0, 5, 8, 10', 'Lấy = KCT'],
  ['14', 'Kho', 'SL tồn đầu', 'Nhập nếu cửa hàng có tồn kho hàng hóa trước khi sử dụng phần mềm, nếu không có thì để trống\nLưu ý: Chỉ đáp ứng khi nhập khẩu thêm mới hàng hóa', 'Lấy = 0'],
  ['15', '', 'Giá trị tồn đầu', 'Giá trị tồn của hàng hóa trước khi sử dụng phần mềm, nếu không có thì để trống\nLưu ý: Chỉ đáp ứng khi nhập khẩu thêm mới hàng hóa', 'Lấy = 0'],
  ['16', '', 'Kho tồn', 'Kho để hàng hóa tồn đầu kỳ\nLưu ý: Chỉ đáp ứng khi nhập khẩu thêm mới hàng hóa', 'Lấy kho bán hàng'],
  ['17', '', 'SL tồn tối thiểu', 'Số lượng hàng hóa tồn tối thiểu - Dùng để thống kê lên báo cáo Kho\\Số lượng tồn tối thiểu.\nLưu ý: Chỉ ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Lấy = 0'],
  ['18', '', 'SL tồn tối đa', 'Số lượng hàng hóa tồn kho tối đa.\nLưu ý: Chỉ ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Lấy = 0'],
  ['19', 'Đơn vị chuyển đổi', 'Đơn vị chuyển đổi', 'Nhập đơn vị chuyển đổi của hàng hóa\nNếu cửa hàng chỉ quản lý hàng hóa theo 1 đơn vị tính thì bỏ qua trường này\nLưu ý: Chỉ ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Không có đơn vị chuyển đổi'],
  ['20', '', 'Tỷ lệ', 'Nhập tỷ lệ chuyển đổi giữa đơn vị tính cơ bản và đơn vị chuyển đổi\nVD: Đơn vị chuyển đổi là Chục, đơn vị cơ bản là Chiếc. 1 Chục = 10 Chiếc => Tỷ lệ = 10', 'Lấy tỷ lệ 1:1'],
  ['21', '', 'Giá mua theo đơn vị chuyển đổi', 'Nhập giá mua của hàng hóa theo đơn vị chuyển đổi, tối đa 14 ký tự, không nhập âm', 'Lấy = Giá mua hàng hóa theo đơn vị tính cơ bản * Tỷ lệ'],
  ['22', '', 'Giá bán theo đơn vị chuyển đổi', 'Nhập giá bán của hàng hóa theo đơn vị chuyển đổi, tối đa 14 ký tự, không nhập âm', 'Lấy = Giá bán hàng hóa theo đơn vị tính cơ bản * Tỷ lệ'],
  ['23', '', 'Đơn vị bán mặc định', 'Để trống: Lấy đơn vị tính cơ bản làm đơn vị bán mặc định\nCó: Lấy đơn vị tính chuyển đổi này làm đơn vị bán mặc định', 'Lấy đơn vị tính cơ bản làm đơn vị bán mặc định'],
  ['24', '', 'Đơn vị nhập mặc định', 'Để trống: Lấy đơn vị tính cơ bản làm đơn vị nhập mặc định\nCó: Lấy đơn vị tính chuyển đổi này làm đơn vị nhập mặc định', 'Lấy đơn vị tính cơ bản làm đơn vị nhập mặc định'],
  ['25', 'Link ảnh hàng hóa', 'Link ảnh hàng hóa', 'Nhập đúng link ảnh cụ thể của hàng hóa (không lấy link tới folder chứa ảnh)', 'Không có ảnh hàng hóa'],
  ['26', 'Kích thước', 'Chiều cao', 'Nhập chiều cao của hàng hóa sau khi gói vào hộp, tối đa 14 ký tự, không nhập âm\nQuy về đơn vị cm, VD: 120 cm thì nhập 120', 'Lấy = 0'],
  ['27', '', 'Chiều rộng', 'Nhập chiều rộng của hàng hóa sau khi gói vào hộp, tối đa 14 ký tự, không nhập âm\nQuy về đơn vị cm, VD: 60 cm thì nhập 60', 'Lấy = 0'],
  ['28', '', 'Chiều dài', 'Nhập chiều dài của hàng hóa sau khi gói vào hộp, tối đa 14 ký tự số, không nhập âm\nQuy về đơn vị cm, VD: 160 cm thì nhập 160', 'Lấy = 0'],
  ['29', '', 'Cân nặng', 'Nhập cân nặng của hàng hóa khi gói vào hộp, tối đa 14 ký tự số, không nhập âm\nQuy về gram, VD: 1 kg nhập = 1000', 'Lấy = 0'],
  ['30', '', 'Vị trí trưng bày', 'Mô tả về vị trí trưng bày của hàng hóa tại cửa hàng để nhân viên dễ lấy hàng (VD: Ở số 3, kệ ngoài cùng)\nTối đa 255 ký tự\nThông tin này ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Không mô tả vị trí trưng bày'],
  ['31', '', 'Vị trí lưu kho', 'Mô tả về vị trí lưu kho của hàng hóa tại kho để nhân viên kho dễ lấy hàng (VD: Góc bên trái kho tầng 2)\nTối đa 255 ký tự\nThông tin này ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Không mô tả vị trí lưu kho'],
  ['32', '', 'Quản lý theo lô, HSD', 'Để trống: Không quản lý theo lô, hạn sử dụng\nCó: Hàng hóa có quản lý theo lô, hạn sử dụng', 'Không quản lý theo lô, hạn sử dụng'],
  ['33', '', 'Cận date', 'Số ngày bán trước so với hạn sử dụng.\nVD: Hạn sử dụng đến ngày 20/10/2020, cần bán trước 1 năm => Nhập Cận date là 365 ngày', 'Để trống'],
  ['34', '', 'Quản lý theo Serial/IMEI', 'Để trống: Không quản lý theo Serial/IMEI\nCó: Hàng hóa có quản lý theo Serial/IMEI', 'Không quản lý theo Serial/IMEI'],
  ['35', '', 'Hiển thị trên màn hình bán hàng', 'Để trống: Có hiển thị hàng hóa trên màn hình bán hàng\nKhông: Ẩn hàng hóa trên màn hình bán hàng\nThông tin này ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Có hiển thị hàng hóa trên màn hình bán hàng'],
  ['36', '', 'Mô tả', 'Mô tả về đặc điểm hàng hóa, các lưu ý cho hàng hóa\nThông tin này ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Không có mô tả'],
  ['37', '', 'Ngừng kinh doanh', 'Để trống: Hàng hóa đang kinh doanh\nCó: Ngừng kinh doanh hàng hóa\nThông tin này ghi nhận cho mẫu mã, không ghi nhận cho hàng hóa chi tiết', 'Hàng hóa đang kinh doanh'],
  ['38', '', 'Bảng giá', 'Điền thêm số cột mới tương ứng với số bảng giá đang có vào cuối file (Sau cột AJ). VD: Cửa hàng có 2 bảng giá Bán buôn 1, Bán buôn 2 thì điền thông tin vào 2 cột AK và AL trên file nhập khẩu với tiêu đề Bán buôn 1, Bán buôn 2.\nLưu ý: Chỉ đáp ứng nhập bảng giá cho ĐVT cơ bản', 'Không có bảng giá'],
];

// ─── Guide sheet ──────────────────────────────────────────────────────────────

const GUIDE_INTRO: string[][] = [
  ['HƯỚNG DẪN SỬ DỤNG TRÊN FILE NHẬP KHẨU HÀNG HÓA'],
  [],
  ['Thông tin nhập', '', '', 'Cách nhập'],
  [
    'Nhập tồn kho ban đầu, số lượng tồn tối thiểu, tối đa (Dành cho cửa hàng có tồn hàng hóa cũ trước khi dùng phần mềm)',
    '', '',
    'Nhập dữ liệu tại các cột từ N đến R',
  ],
  [
    'Nhập đơn vị tính chuyển đổi (Dành cho cửa hàng quản lý theo nhiều đơn vị tính)',
    '', '',
    'Nhập dữ liệu tại các cột từ S đến X\nCột S – đơn vị chuyển đổi: nhập tên đơn vị chuyển đổi\nCột T- Tỷ lệ: nhập tỷ lệ quy đổi giữa đơn vị chuyển đổi so với đơn vị tính cơ bản, ví dụ: \n     đơn vị tính cơ bản là Chiếc\n     đơn vị tính chuyển đổi là Set, 1 Set = 6 Chiếc\n     => nhập Tỷ lệ là 6',
  ],
  [
    'Nhập kích cỡ trọng lượng, tỷ trọng hàng hóa',
    '', '',
    'Nhập dữ liệu tại các cột từ Y đến AB\nCột kích cỡ: Nhập đơn vị cm. VD: 120\nCột trọng lượng: Nhập theo đơn vị gram. VD: 500',
  ],
  [
    'Nhập bảng giá (Dành cho cửa hàng bán hàng hóa theo nhiều giá)',
    '', '',
    'Điền thêm số cột mới tương ứng với số bảng giá đang có vào cuối file (Sau cột AJ). VD: Cửa hàng có 2 bảng giá Bán buôn 1, Bán buôn 2 thì điền thông tin vào 2 cột AK và AL trên file nhập khẩu với tiêu đề Bán buôn 1, Bán buôn 2. Xem thêm ở ví dụ mẫu TH6 bên dưới. \nLưu ý: Chỉ đáp ứng nhập bảng giá cho ĐVT cơ bản',
  ],
  [
    'Nhập vị trí trưng bày, vị trí lưu kho',
    '', '',
    'Nhập dữ liệu dạng text tại các cột AD và AE',
  ],
  [
    'Nhập quản lý hàng hóa theo Số lô, hạn sử dụng, Cận date',
    '', '',
    'Chọn từ cột AE đến cột AI, nhấn chuột phải, chọn Unhide\nCột Quản lý theo lô, HSD: chọn Có nếu hàng hóa quản lý theo lô, hạn sử dụng\nCột Cận Date: Cận date trước bao nhiêu ngày so với hạn sử dụng',
  ],
  [
    'Nhập quản lý hàng hóa theo Serial/IMEI',
    '', '',
    'Tại cột AH, chọn Có nếu hàng hóa quản lý theo Serial/IMEI',
  ],
  [
    'Mã SKU, Mã vạch',
    '', '',
    'Nếu nhập: Chương trình lấy mã đã nhập. \nNếu để trống: Chương trình tự sinh.',
  ],
  [
    'Mã SKU mẫu mã',
    '', '',
    'Các dòng hàng hóa có chung Mã SKU mẫu mã được hiểu là cùng 1 mẫu mã (Hàng hóa cha).\nLưu ý: Nếu là Mẫu mã (Hàng hóa cha) thì không nhập trường này, chỉ cần nhập trường Mã SKU',
  ],
  [
    'Màu, Size',
    '', '',
    'Nhập màu sắc, size của hàng hóa\nLưu ý: Nếu nhập Hàng hóa chi tiết (Hàng hóa con) cần nhập ít nhất 1 thông tin Màu hoặc Size',
  ],
  [
    'Nhập thuế suất hàng hóa (Dành cho cửa hàng có áp dụng theo dõi thuế)',
    '', '',
    'Chọn từ cột L đến cột N, nhấn chuột phải, chọn Unhide\nNhập nếu cửa hàng có hàng hóa với nhiều mức thuế suất khác nhau\nNhập trong các giá trị: KCT, 0, 5, 8, 10',
  ],
  [
    'Giá bán',
    '', '',
    'Nếu cửa hàng áp dụng bán hàng với đơn giá là giá trước thuế, nhập giá trước thuế.\nNếu cửa hàng áp dụng bán hàng với đơn giá là giá sau thuế, nhập giá sau thuế.\nKhông nhập số âm',
  ],
];

const GUIDE_TH_OVERVIEW: string[][] = [
  [],
  ['VÍ DỤ MẪU CÁC TRƯỜNG HỢP PHỔ BIẾN (Nhấn vào từng trường hợp để xem hướng dẫn tương ứng)'],
  [],
  ['', 'Chia Màu/Size', 'Nhiều đơn vị tính'],
  ['TH1', 'Không', 'Không'],
  ['TH2', 'Không', 'Có'],
  ['TH3', 'Có', 'Không'],
  ['TH4', 'Có', 'Có'],
  ['TH5', 'Giá mỗi màu/size khác nhau'],
  ['TH6', 'Hàng hóa bán theo nhiều bảng giá'],
];

const GUIDE_TH1: string[][] = [
  [],
  ['TH1: HÀNG HÓA KHÔNG CÓ MÀU/SIZE, KHÔNG QUẢN LÝ THEO NHIỀU ĐƠN VỊ TÍNH'],
  [],
  ['- Thông tin cửa hàng có'],
  [],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Giá mua', 'Giá bán'],
  ['ASMTN', '100025', 'Áo sơ mi thắt nơ', 'Áo sơ mi', 'Chiếc', '200.000', '300.000'],
  ['QBR', '125639', 'Quần bò rách', 'Quần bò', 'Chiếc', '250.000', '450.000'],
  [],
  [' => Nhập trên file như sau'],
  [],
  ['Không có Mã SKU/Mã vạch: Để trống ô Mã SKU/Mã vạch'],
  IH,
  ['', '', '', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', '', '', '200.000', '300.000'],
  ['', '', '', '', 'Quần bò rách', 'QB', 'Quần bò', 'Chiếc', '', '', '250.000', '450.000'],
  [],
  ['Đã có Mã SKU/Mã vạch: Nhập tại ô Mã SKU/Mã vạch'],
  IH,
  ['ASMTN', '100025', '', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', '', '', '200.000', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0'],
  ['QBR', '125639', '', '', 'Quần bò rách', 'QB', 'Quần bò', 'Chiếc', '', '', '250.000', '450.000'],
  [],
  [' => Kết quả trên chương trình'],
  [],
  RH,
  ['ASMTN', '100025', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', '', '', '200.000', '300.000'],
  ['QBR', '125639', 'Quần bò rách', 'QB', 'Quần bò', 'Chiếc', '', '', '250.000', '450.000'],
];

const GUIDE_TH2: string[][] = [
  [],
  ['TH2: HÀNG HÓA KHÔNG CÓ MÀU/SIZE, QUẢN LÝ THEO NHIỀU ĐƠN VỊ TÍNH'],
  [],
  ['- Thông tin cửa hàng có'],
  [],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Nhóm hàng hóa', 'ĐVT', 'Giá mua', 'Giá bán'],
  ['ASMTN', '100025', 'Áo sơ mi thắt nơ', 'Áo sơ mi', 'Chiếc', '200.000', '300.000'],
  ['QBR', '125639', 'Quần bò rách', 'Quần bò', 'Chiếc', '250.000', '450.000'],
  [],
  ['- Thông tin đơn vị chuyển đổi của Áo sơ mi thắt nơ', '', '', '', '- Thông tin đơn vị chuyển đổi của Quần bò rách'],
  [],
  ['Đơn vị chuyển đổi', 'Tỷ lệ', 'Giá bán', '', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Giá bán'],
  ['Hộp', '2', '600.000', '', 'Hộp', '2', '900.000'],
  ['Chục', '10', '3.000.000', '', 'Chục', '10', '4.500.000'],
  [],
  [' => Nhập trên file như sau (Thông tin đơn vị chuyển đổi nhập tại cột R đến cột W, mỗi đơn vị tính chuyển đổi nhập 1 dòng ngay bên dưới)'],
  [],
  ['Không có Mã SKU/Mã vạch: Để trống ô Mã SKU/Mã vạch', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Đây là cột nhập đơn vị tính chuyển đổi'],
  IH,
  ['', '', '', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', '', '', '200.000', '300.000', '', '', '', '', '', 'Hộp', '2', '', '600.000'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Chục', '10', '', '3.000.000'],
  ['', '', '', '', 'Quần bò rách', 'QB', 'Quần bò', 'Chiếc', '', '', '250.000', '450.000', '', '', '', '', '', 'Hộp', '2', '', '900.000'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Chục', '10', '', '4.500.000'],
  [],
  ['Đã có Mã SKU/Mã vạch: Nhập tại ô Mã SKU/Mã vạch', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Đây là cột nhập đơn vị tính chuyển đổi'],
  IH,
  ['ASMTN', '10000015', '', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', '', '', '200.000', '300.000', '', '', '', '', '', 'Hộp', '2', '', '600.000'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Chục', '10', '', '3.000.000'],
  ['QBR', '10000016', '', '', 'Quần bò rách', 'QB', 'Quần bò', 'Chiếc', '', '', '250.000', '450.000', '', '', '', '', '', 'Hộp', '2', '', '900.000'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Chục', '10', '', '4.500.000'],
  [],
  [' => Kết quả trên chương trình'],
  [],
  RH,
  ['ASMTN', '100025', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', '', '', '200.000', '300.000'],
  ['QBR', '125639', 'Quần bò rách', 'QB', 'Quần bò', 'Chiếc', '', '', '250.000', '450.000'],
  [],
  ['- Thông tin đơn vị chuyển đổi sinh cho Áo sơ mi thắt nơ', '', '', '', '', '- Thông tin đơn vị chuyển đổi sinh cho Quần bò rách'],
  [],
  ['Đơn vị chuyển đổi', 'Tỷ lệ', 'Mô tả', 'Giá bán', '', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Mô tả', 'Giá bán'],
  ['Hộp', '2', '1 Hộp = 2 Chiếc', '600.000', '', 'Hộp', '2', '1 Hộp = 2 Chiếc', '900.000'],
  ['Chục', '10', '1 Chục = 10 Chiếc', '3.000.000', '', 'Chục', '10', '1 Chục = 10 Chiếc', '4.500.000'],
];

const GUIDE_TH3: string[][] = [
  [],
  ['TH3: HÀNG HÓA CÓ NHIỀU MÀU/SIZE, GIÁ MỖI MÀU/SIZE GIỐNG NHAU, KHÔNG QUẢN LÝ THEO NHIỀU ĐƠN VỊ TÍNH'],
  [],
  ['- Thông tin cửa hàng có: Áo sơ mi (ASM) gồm các Màu/Size:'],
  [],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size', 'Giá bán'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '350.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '350.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '350.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '350.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '350.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '350.000'],
  [],
  [' => Nhập trên file như sau'],
  [],
  ['Không có Mã SKU/Mã vạch: Để trống ô Mã SKU/Mã vạch'],
  IH,
  ['ASMTN', '', '', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh, Đỏ', 'S, M, L', '', '350.000'],
  [],
  ['Đã có Mã SKU/Mã vạch: Nhập tại ô Mã SKU/Mã vạch, cột Mã SKU mẫu mã nhập chung 1 mã'],
  IH,
  ['ASMTN-XANH-S', '10000015', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '', '350.000'],
  ['ASMTN-XANH-M', '10000016', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '', '350.000'],
  ['ASMTN-XANH-L', '10000017', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '', '350.000'],
  ['ASMTN-DO-S', '10000018', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '', '350.000'],
  ['ASMTN-DO-M', '10000019', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '', '350.000'],
  ['ASMTN-DO-L', '10000020', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '', '350.000'],
  [],
  [' => Kết quả trên chương trình'],
  [],
  ['- Sinh mẫu mã'],
  ['Mã SKU mẫu mã', 'Mã vạch', 'Tên mẫu mã', 'Mã nhóm hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size', 'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu', 'SL tồn tối đa', 'Kho tồn', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Giá mua theo đơn vị chuyển đổi', 'Giá bán theo đơn vị chuyển đổi', 'Đơn vị bán mặc định', 'Đơn vị nhập mặc định', 'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng', 'Vị trí trưng bày', 'Vị trí lưu kho', 'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh'],
  ['ASMTN', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh, Đỏ', 'S, M, L', '', '350.000'],
  [],
  ['- Sinh hàng hóa chi tiết cho Màu/Size'],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Màu', 'Size', 'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Xanh', 'S', '', '350.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Xanh', 'M', '', '350.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Xanh', 'L', '', '350.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Đỏ', 'S', '', '350.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Đỏ', 'M', '', '350.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Đỏ', 'L', '', '350.000'],
];

const GUIDE_TH4: string[][] = [
  [],
  ['TH4: HÀNG HÓA CÓ NHIỀU MÀU/SIZE, GIÁ MỖI MÀU/SIZE GIỐNG NHAU, QUẢN LÝ THEO NHIỀU ĐƠN VỊ TÍNH'],
  [],
  ['- Thông tin cửa hàng có: Áo sơ mi (ASM) gồm các Màu/Size:'],
  [],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size', 'Giá bán'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '350.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '350.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '350.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '350.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '350.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '350.000'],
  [],
  ['- Thông tin đơn vị chuyển đổi cửa hàng đang có của mẫu mã Áo sơ mi'],
  [],
  ['Đơn vị chuyển đổi', 'Tỷ lệ', 'Giá mua', 'Giá bán'],
  ['Hộp', '2', '', '700.000'],
  ['Chục', '10', '', '3.500.000'],
  [],
  [' => Nhập trên file như sau (Thông tin đơn vị chuyển đổi nhập tại cột R đến cột W, mỗi đơn vị tính chuyển đổi nhập 1 dòng ngay bên dưới)'],
  [],
  ['Không có Mã SKU/Mã vạch: Để trống ô Mã SKU/Mã vạch', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Đây là cột nhập đơn vị tính chuyển đổi'],
  IH,
  ['', '', '', '', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh, Đỏ', 'S, M, L', '', '350.000', '1', '250.000', '', '', '', 'Hộp', '2', '', '700.000'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Chục', '10', '', '3.500.000'],
  [],
  ['Đã có Mã SKU/Mã vạch: Nhập tại ô Mã SKU/Mã vạch, cột Mã SKU mẫu mã nhập chung 1 mã', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Đây là cột nhập đơn vị tính chuyển đổi'],
  IH,
  ['ASMTN-XANH-S', '10000015', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '', '350.000,00', '1,00', '250.000,00', '', '', '', 'Hộp', '2', '', '700.000,00'],
  ['', '', 'ASMTN', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Chục', '10', '', '3.500.000,00'],
  ['ASMTN-XANH-M', '10000016', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '', '350.000,00', '1,00', '250.000,00'],
  ['ASMTN-XANH-L', '10000017', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '', '350.000,00', '2,00', '250.000,00'],
  ['ASMTN-DO-S', '10000018', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '', '350.000,00', '3,00', '250.000,00'],
  ['ASMTN-DO-M', '10000019', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '', '350.000,00', '2,00', '250.000,00'],
  ['ASMTN-DO-L', '10000020', 'ASMTN', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '', '350.000,00', '0,00', '250.000,00'],
  [],
  [' => Kết quả trên chương trình'],
  [],
  ['- Sinh mẫu mã ASM'],
  ['Mã SKU mẫu mã', 'Mã vạch', 'Tên mẫu mã', 'Mã nhóm hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size', 'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu', 'SL tồn tối đa', 'Kho tồn', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Mô tả', 'Giá mua theo đơn vị chuyển đổi', 'Giá bán theo đơn vị chuyển đổi', 'Đơn vị bán mặc định', 'Đơn vị nhập mặc định', 'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng', 'Vị trí trưng bày', 'Vị trí lưu kho', 'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh'],
  ['ASMTN', '10000001', 'Áo sơ mi thắt nơ', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh, Đỏ', 'S, M, L', '', '350.000'],
  [],
  ['- Đơn vị chuyển đổi sinh cho ASM'],
  [],
  ['Đơn vị chuyển đổi', 'Tỷ lệ', 'Mô tả', 'Giá bán'],
  ['Hộp', '2', '1 Hộp = 2 Chiếc', '600.000'],
  ['Chục', '10', '1 Chục = 10 Chiếc', '3.000.000'],
  [],
  ['- Hàng hóa chi tiết cho Màu/Size'],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size', 'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu', 'SL tồn tối đa', 'Kho tồn', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Mô tả', 'Giá mua theo đơn vị chuyển đổi', 'Giá bán theo đơn vị chuyển đổi', 'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng', 'Vị trí trưng bày', 'Vị trí lưu kho', 'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '', '350.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '', '350.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '', '350.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '', '350.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '', '350.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '', '350.000'],
];

const GUIDE_TH5: string[][] = [
  [],
  ['TH5: HÀNG HÓA CÓ NHIỀU MÀU/SIZE, GIÁ MỖI MÀU/SIZE KHÁC NHAU'],
  [],
  ['- Thông tin cửa hàng có'],
  [],
  ['', '', '', '', '', '', '', 'Giá bán khác nhau'],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Màu', 'Size', 'Tên nhóm hàng hóa', 'ĐVT', 'Giá bán'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Xanh', 'S', 'Áo sơ mi', 'Chiếc', '300.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Xanh', 'M', 'Áo sơ mi', 'Chiếc', '320.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Xanh', 'L', 'Áo sơ mi', 'Chiếc', '350.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Đỏ', 'S', 'Áo sơ mi', 'Chiếc', '300.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Đỏ', 'M', 'Áo sơ mi', 'Chiếc', '320.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Đỏ', 'L', 'Áo sơ mi', 'Chiếc', '350.000'],
  [],
  [' => Nhập trên file như sau'],
  ['', '', '', '', '', '', '', '', 'Ghi giá bán khác nhau'],
  IH,
  ['ASMTN-XANH-S', '10000015', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '', '300.000'],
  ['ASMTN-XANH-M', '10000016', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '', '320.000'],
  ['ASMTN-XANH-L', '10000017', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '', '350.000'],
  ['ASMTN-DO-S', '10000018', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '', '300.000'],
  ['ASMTN-DO-M', '10000019', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '', '320.000'],
  ['ASMTN-DO-L', '10000020', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '', '350.000'],
  [],
  [' => Kết quả trên chương trình'],
  [],
  ['- Sinh mẫu mã ASM'],
  ['Mã SKU mẫu mã', 'Mã vạch', 'Tên mẫu mã', 'Màu', 'Size', 'Mã nhóm hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu', 'SL tồn tối đa', 'Kho tồn', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Giá mua theo đơn vị chuyển đổi', 'Giá bán theo đơn vị chuyển đổi', 'Đơn vị bán mặc định', 'Đơn vị nhập mặc định', 'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng', 'Vị trí trưng bày', 'Vị trí lưu kho', 'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh'],
  ['ASM', '10000001', 'ASM', 'Xanh, Đỏ', 'S, M, L', 'ASM', 'Áo sơ mi', 'Chiếc', '', '300.000'],
  [],
  ['- Hàng hóa chi tiết cho Màu/Size'],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Màu', 'Size', 'Mã nhóm hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Giá mua', 'Giá bán', 'SL tồn đầu', 'Giá trị tồn đầu', 'SL tồn tối thiểu', 'SL tồn tối đa', 'Kho tồn', 'Đơn vị chuyển đổi', 'Tỷ lệ', 'Giá mua theo đơn vị chuyển đổi', 'Giá bán theo đơn vị chuyển đổi', 'Đơn vị bán mặc định', 'Đơn vị nhập mặc định', 'Chiều cao', 'Chiều rộng', 'Chiều dài', 'Cân nặng', 'Vị trí trưng bày', 'Vị trí lưu kho', 'Hiển thị trên màn hình bán hàng', 'Mô tả', 'Ngừng kinh doanh'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Xanh', 'S', 'ASM', 'Áo sơ mi', 'Chiếc', '', '300.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Xanh', 'M', 'ASM', 'Áo sơ mi', 'Chiếc', '', '320.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Xanh', 'L', 'ASM', 'Áo sơ mi', 'Chiếc', '', '350.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Đỏ', 'S', 'ASM', 'Áo sơ mi', 'Chiếc', '', '300.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Đỏ', 'M', 'ASM', 'Áo sơ mi', 'Chiếc', '', '320.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Đỏ', 'L', 'ASM', 'Áo sơ mi', 'Chiếc', '', '350.000'],
];

const GUIDE_TH6: string[][] = [
  [],
  ['TH6: HÀNG HÓA BÁN THEO NHIỀU BẢNG GIÁ'],
  [],
  ['- Thông tin cửa hàng có'],
  [],
  ['Mã SKU', 'Mã vạch', 'Tên hàng hóa', 'Tên nhóm hàng hóa', 'ĐVT', 'Màu', 'Size', 'Giá bán buôn 1', 'Giá bán buôn 2'],
  ['ASMTN-XANH-S', '10000015', 'Áo sơ mi thắt nơ (Xanh/S)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '250.000', '280.000'],
  ['ASMTN-XANH-M', '10000016', 'Áo sơ mi thắt nơ (Xanh/M)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '250.000', '280.000'],
  ['ASMTN-XANH-L', '10000017', 'Áo sơ mi thắt nơ (Xanh/L)', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '250.000', '280.000'],
  ['ASMTN-DO-S', '10000018', 'Áo sơ mi thắt nơ (Đỏ/S)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '250.000', '280.000'],
  ['ASMTN-DO-M', '10000019', 'Áo sơ mi thắt nơ (Đỏ/M)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '250.000', '280.000'],
  ['ASMTN-DO-L', '10000020', 'Áo sơ mi thắt nơ (Đỏ/L)', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '250.000', '280.000'],
  [],
  [' => Nhập trên file như sau (Điền thông tin bảng giá vào 2 cột AJ và AK tương ứng với 2 bảng giá)'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Đây cột bổ sung của bảng giá'],
  IH6,
  ['ASMTN-XANH-S', '10000015', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-XANH-M', '10000016', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '', '320.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-XANH-L', '10000017', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Xanh/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '', '350.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-DO-S', '10000018', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-DO-M', '10000019', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '', '320.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-DO-L', '10000020', 'ASM', 'Áo sơ mi thắt nơ', 'Áo sơ mi thắt nơ (Đỏ/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '', '350.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  [],
  [' => Kết quả trên chương trình'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Đây cột bổ sung của bảng giá'],
  RH6,
  ['ASMTN-XANH-S', '100025', 'Áo sơ mi thắt nơ (Xanh/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'S', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-XANH-M', '100568', 'Áo sơ mi thắt nơ (Xanh/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'M', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-XANH-L', '100298', 'Áo sơ mi thắt nơ (Xanh/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Xanh', 'L', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-DO-S', '100356', 'Áo sơ mi thắt nơ (Đỏ/S)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'S', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-DO-M', '100256', 'Áo sơ mi thắt nơ (Đỏ/M)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'M', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
  ['ASMTN-DO-L', '125634', 'Áo sơ mi thắt nơ (Đỏ/L)', 'ASM', 'Áo sơ mi', 'Chiếc', 'Đỏ', 'L', '', '300.000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '250.000', '280.000'],
];

export const STATIC_GUIDE_GRID: string[][] = [
  ...GUIDE_INTRO,
  ...GUIDE_TH_OVERVIEW,
  ...GUIDE_TH1,
  ...GUIDE_TH2,
  ...GUIDE_TH3,
  ...GUIDE_TH4,
  ...GUIDE_TH5,
  ...GUIDE_TH6,
];
